
[core]

name: gladius

displayText: Gladius LHV
displayDescription: -light hover vehicle "Gladius"\n-splash attack \n-reduced building damage

displayText_ru:Гладиус ЛХ
displayDescription_ru:-Легкий ховер "Гладиус"\n-Атака по области\n-Уменьшенный урон по строениям

class: CustomUnitMetadata
price: 750
maxHp: 350
armour:2
mass: 2000

techLevel: 1
buildSpeed: 13s
#availableInDemo: true

radius: 12
displayRadius: 12

isBio: false
softCollisionOnAll: 0

[graphics]
total_frames: 3

teamColorsOnTurret: true
image:        gladius.png
image_wreak:  gladius_wreck.png
image_turret: gladius_turret_base.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 1

animation_idle_start: 0
animation_idle_end: 2
animation_idle_speed: 1


dustEffect: true
splastEffect: true

[hiddenAction_retreat]
autoTrigger: if self.isControlledByAi() and self.hp(lessThan=175) and not self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
temporarilyAddTags: retreat

[hiddenAction_retreating]
autoTrigger: if self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
allowMultipleInQueue:false

[hiddenAction_active]
autoTrigger: if self.tags(includes='retreat') and (self.hp() == self.maxHp())
temporarilyRemoveTags: retreat

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 10
turretTurnSpeed: 3


maxAttackRange: 130
shootDelay: 50
[turret_2]
#
x: 0
y: 0
image:gladius_turret_barrel.png
attachedTo:1
slave:true

projectile: 1

recoilOffset: -5
recoilReturnTime: 2.00s

turnSpeed: 3
barrelY: 15

canShoot: true

shoot_sound:ROOT:sounds\shotgun_fire_1.wav
shoot_sound_vol:0.50
shoot_flame:small

[turret_1]
x: 0
y: 0
projectile: 1
canShoot:false



[turret_3]
x: 0
y: 0
invisible:true
copyFrom:2
attachedTo:1
slave:true

[turret_4]
x: 0
y: 0
invisible:true
copyFrom:2
attachedTo:1
slave:true

[turret_5]
x: 0
y: 0
invisible:true
copyFrom:2
attachedTo:1
slave:true

[turret_6]
x: 0
y: 0
invisible:true
copyFrom:2
attachedTo:1
slave:true

[turret_7]
x: 0
y: 0
invisible:true
copyFrom:2
attachedTo:1
slave:true

[turret_8]
x: 0
y: 0
invisible:true
copyFrom:2
attachedTo:1
slave:true

[turret_9]
x: 0
y: 0
invisible:true
copyFrom:2
attachedTo:1
slave:true

[turret_10]
x: 0
y: 0
invisible:true
copyFrom:2
attachedTo:1
slave:true


[projectile_1]
areaDamage: 5
areaRadius:45
areaDamageNoFalloff:true
life: 40
speed: 8
armourIgnoreAmount:3

shieldDamageMultiplier:0.85
buildingDamageMultiplier:0.5

targetGroundSpread:40
targetGround:true

drawSize: 1
image: ROOT:shared\graphics\pellet.png

[movement]
movementType: hover
moveSpeed: 1.2
moveAccelerationSpeed: 0.40
moveDecelerationSpeed: 0.30
reverseSpeedPercentage:0.3
targetHeight:3
maxTurnSpeed: 5.0
turnAcceleration: 0.55

moveSlidingMode :false
moveIgnoringBody:false

[ai]
buildPriority:0.7