[core]

name: barracks_t2
class: CustomUnitMetadata
maxHp: 1200
price: 1700
mass: 1000
nanoFactorySpeed: 1.25
techLevel:2

displayText: Infantry barracks Tier 2
displayDescription: -Dominion's upgraded soldier barracks \n-produces infantry which are fragile but have large amounts of firepower, and are mobile and versatile.\n-The upgrade gives access to better weapons and veteran units\n-existance of a t2 factory allows for faster and cheaper upgrades of t1 factories of this type

displayText_ru: Пехотные бараки Т2
displayDescription_ru: -Улучшенные Пехотные бараки доминиона \n-Производит пехоту, она уязвима но имеет большую огневую мощь, мобильна и универсальна.\n-Улучшение даёт доступ к более мощному оружию и ветеранским юнитам\n-Наличие т2 завода позволит быстрее и дешевле прокачать остальные т1 заводы этого типа

tags:T2_infantry
radius: 60
displayRadius:60

buildSpeed: 30s

#footprint used for collisions with units (left, up, right, down)
footprint: -1,-1,1,2

#used for placement, and placement of other buildings
constructionFootprint: -1,-1,1,2

isBuilding: true
explodeTypeOnDeath: building

canBuild_1_name: setRally
canBuild_1_pos:  0.1

copyFrom:barracks.ini

canBuild_7_name:sturmpioneer,jaeger,stosstruppe,schockwelle,faust,klatsche,scharfschutze,ungetum,field_gun,hoverganger
canBuild_7_pos:8
[graphics]

image: barracks_t2.png
image_wreak: barracks_t2_wreck.png
image_back:barracks_back.png

image_shadow: auto
shadowOffsetX:1
shadowOffsetY:1

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false

[action_upgrade]
isLocked:true
text:Upgrade
pos:0.1
isVisible: if numberOfUnitsInTeam(withTag="T2_infantry") == 0
isLockedMessage: We did not invent this yet
price:2000
buildSpeed:40s

allowMultipleInQueue:false
iconImage: SHARED:icon_upgrade.png
displayType: upgrade
description:Upgrade to T2 
#convertTo: barracks_t3

[action_upgrade_consecutive]
isLocked:true
text:Upgrade
pos:0.1
isVisible: if numberOfUnitsInTeam(withTag="T2_infantry") > 0
isLockedMessage: We did not invent this yet
price:1000
buildSpeed:20s

allowMultipleInQueue:false
iconImage: SHARED:icon_upgrade.png
displayType: upgrade
description:Upgrade to T2 /n-(cheaper due to already having a T2 factory of this type)
#convertTo: barracks_t3
[arm_1]
x:0
y:0
image_end:barracks_t2_door.png


[animation_openDoor]

onActions: queuedUnits
onActionsQueuedUnitPlayAt: 0.8

blendIn: 1s
blendOut: 4s

arm1_0: {x:0, y:26}

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1

[ai]
upgradedFrom: barracks
