
[core]
name: hawk
class: CustomUnitMetadata
price: 1900
maxHp: 1000
armour:2
mass: 4000

copyFrom:ROOT:Templates\customEffects.template

energyMax: 30
energyRegen: 0.025
energyRegenWhenRecharging:0.10
energyNeedsToRechargeToFull: true

displayText: Hawk interceptor 
displayDescription:- A jet interceptor armed with an autocannon and 2 mg's \n- fast, durable, and has high burst damage \n- weak to being chased

displayText_ru: Перехватчик Ястреб
displayDescription_ru:Реактивный перехватчик вооруженный автопушкой и 2 пулемётами\n-Быстрый, крепкий, имеет высокий урон за заход\n-Слаб при его приследовании

techLevel: 2
buildSpeed: 18.0s

radius: 24

isBio: false

softCollisionOnAll: 40
fogOfWarSightRange: 19
tags: air

[graphics]
total_frames: 5
drawLayer:air

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 20

animation_moving_start: 1
animation_moving_end: 4
animation_moving_speed: 0.5

image:        hawk.png
image_wreak:  hawk_wreck.png
image_turret: hawk_gun.png
imageScale:0.80
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1

[attack]

canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
attackMovement: bomber
turretSize: 18
turretTurnSpeed: 5.5
maxAttackRange: 600
shootDelay: 5
turretMultiTargeting:true
isMelee:true
#retreat distance should be same as attack range, actual range is to be changed under turret
[turret_retreatDistance]
x: 0
y: 0
invisible: true
shoot_flame: NONE
canShoot:true
limitingRange:800
projectile:dummy
delay:100

[attachment_RealGun]
x:0
y:0

idleDir: 0
isUnselectable: true
deattachIfWantingToMove: false
resetRotationWhenNotAttacking: true
prioritizeParentsMainTarget: true
isVisible:true
setDrawLayerOnTop:true
onCreateSpawnUnitOf:hawk_gun
rotateWithParent:true

[projectile_dummy]
life: 1

directDamage: 0
areaDamage: 0
areaRadius: 0

speed: 1
instant: false

invisible: true
hitSound: false
explodeEffect: NONE
explodeEffectOnShield: NONE
trailEffect: false
largeHitEffect: false

[turret_2]
x: 0
y: 0

barrelX:-10
barrelY:15
barrelOffsetX_onOddShots: 20
invisible:true
idleDir:0
canAttackCondition: if self.flying
canShoot: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
energyUsage:1
projectile: dummy
limitingRange:300
turnSpeed: 20
canAttackMaxAngle:70
limitingAngle:70

[turret_3]
x: 0
y: 24
size:10
idleDir:0
canAttackCondition: if self.flying
canShoot: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
projectile: dummy

energyUsage:2
delay:7

limitingRange:380
turnSpeed: 0.0
canAttackMaxAngle:70
limitingAngle:70

[projectile_1]
directDamage: 25
life: 60
speed: 15

frame: 5
color: #ae0000
drawSize: 1

lightColor: #ae0000
lightSize:0.4

explodeEffect:CUSTOM:bullet_hit

[projectile_2]
directDamage: 12
life: 60
speed: 10

frame: 5
drawSize: 0.6

explodeEffect:CUSTOM:bullet_hit

[movement]
movementType: AIR
moveSpeed: 3.0
moveAccelerationSpeed: 0.7
moveDecelerationSpeed: 0.08
reverseSpeedPercentage:0.0
landOnGround: onlyIdle


maxTurnSpeed: 8.0
turnAcceleration:0.15


moveSlidingMode :true
moveIgnoringBody:false


targetHeight:60
heightChangeRate:0.8

slowDeathFall: true
