
[core]

name: ballistae

displayText: Ballistae Tank
displayDescription: -Self propelled heavy tank hunter:"Ballistae"\n-Powerfull cannon with low firerate, and a small mg\n-vulnerable if unsupported\n-ground attack \n-thorium powered engine allows it to have decent speed despite the weight and size\n-blow a head sized hole through anything, just as the founding fathers intended.

copyFrom:ROOT:Templates\customEffects.template

class: CustomUnitMetadata
price: credits=6000,thorium=550
maxHp: 4200
armour:5
mass: 2000

techLevel: 3
buildSpeed: 60s
#availableInDemo: true

radius: 28
displayRadius: 33

isBio: false
softCollisionOnAll: 0

[graphics]
total_frames: 4
imageScale:0.85
scaleTurretImagesTo:32
teamColorsOnTurret: true
image:       ballistae.png
image_wreak:  ballistae_wreck.png
image_turret: ballistae_turret_base.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 0
animation_moving_end: 3
animation_moving_speed: 1.4


dustEffect: true

[hiddenAction_retreat]
autoTrigger: if self.isControlledByAi() and self.hp(lessThan=200) and not self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
temporarilyAddTags: retreat

[hiddenAction_retreating]
autoTrigger: if self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
allowMultipleInQueue:false

[hiddenAction_active]
autoTrigger: if self.tags(includes='retreat') and (self.hp() == self.maxHp())
temporarilyRemoveTags: retreat

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 10
turretTurnSpeed: 2


maxAttackRange: 300
shootDelay: 330

[turret_3]
#
x:0
y:23

image:ballistae_mg.png

#slave:true
projectile: 2

canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
delay:6
size:10

idleDir:0
limitingRange:180
limitingAngle:60

turnSpeed:4

recoilOffset: -1.5
recoilReturnTime: 0.15s

shoot_sound:ROOT:sounds\smg_fire.wav
shoot_sound_vol:0.25
shoot_flame:small
shoot_light:#FFccCCEE

canShoot: true

[turret_2]
#
x: 0
y: 15
image:ballistae_turret_barrel.png
attachedTo:1
slave:true

projectile: 1

warmup:20

recoilOffset: -10
recoilReturnTime: 4.00s

turnSpeed: 3
barrelY: 67

canShoot: true

shoot_sound:ROOT:sounds\heavy_cannon_fire_1.wav
shoot_sound_vol:0.400
shoot_flame:large


[turret_1]
x: 0
y: -12
projectile: 1
canShoot:false


[projectile_1]
directDamage: 1100
areaDamage: 100
areaRadius: 40
life: 120
speed: 10
color:#ff5100
image: ROOT:shared\graphics\shell.png
drawSize: 1.2


[projectile_2]
directDamage: 15
life: 80
speed: 8

frame: 5

drawSize: 0.8

explodeEffect:CUSTOM:bullet_hit

[movement]
movementType: LAND
moveSpeed: 0.6
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.10
reverseSpeedPercentage:0.90

maxTurnSpeed: 1.5
turnAcceleration: 0.15

moveSlidingMode :false
moveIgnoringBody:false

[ai]
buildPriority:0.7