[core]

name: sturmpioneer

tags:infantry,radar
displayText: Sturmpioneer
displayDescription: -Dominion's Combat engineers\n-Well trained and armed\n-primarily used for demolishing enemy buildings and building heavier fortifications, can also perform sapper duties\n-can quickly repair buildings and vehicles\n-Land attack\n-these guys have a couple screws loose, and they will make it the enemy's problem

displayText_ru: Штурмпионер
displayDescription_ru:-Боевые инжинеры доминиона\n-Хорошо обучены и вооружены\n-в основном используются для сноса вражеских строений и возведения тяжёлых укреплений, также могут выполнять сапёрные работы\n-Также могут быстро ремонтировать строения и юнитов\n-Наземная атака\n-У этих ребят давно поехала крыша, и это станет проблемой противника.
copyFrom:ROOT:Templates\customEffects.template

#-temporarily disabled
#canRepairUnitsOnlyWithTags:repairable
canReclaimResources: true
class: CustomUnitMetadata
price: 1000
maxHp: 400
mass: 100
armour:3
selfRegenRate:0.1

energyMax:26.0
energyRegen:0.01
energyNeedsToRechargeToFull:true
energyRegenWhenRecharging:0.10

isBuilder: true

nanoRange:150
nanoBuildSpeed: 2.0
nanoRepairSpeed:0.8

canRepairBuildings: true
canRepairUnits : true
isUnrepairableUnit:true

techLevel: 2
buildSpeed: 25s
#availableInDemo: true

radius: 8
displayRadius: 8

autoRepair: true
isBio: true
softCollisionOnAll: 8

[graphics]
#total_frames: 8
imageScale:0.90
image:        sturmpioneer.png
image_wreak:  none
image_turret: sturmpioneer_gun.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


#animation_moving_start: 0
#animation_moving_end: 7
#animation_moving_speed: 2

[hiddenAction_repair]
autoTrigger: if not self.hasActiveWaypoint(type='repair') and self.numberOfUnitsInTeam(withTag='retreat', withinRange=300, greaterThan=0)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: retreat
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: repair
allowMultipleInQueue: false

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

isFixedFiring: true

turretSize: 5
turretTurnSpeed: 5


maxAttackRange: 180

turretRotateWithBody: true

shootDelay: 12

[turret_1]
#nano turret (nano must be slot 1)
x: 0
y: 0
invisible: true
warmup:10

canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turnSpeedAcceleration: 1.0

[turret_2]
#
x: 4.0
y: -1.0
canAttackMaxAngle:15
canAttackFlyingUnits: false
canAttackLandUnits:   true
projectile: 1

size:18

energyUsage:1
turnSpeedAcceleration: 1.0

recoilOffset: -1.5
recoilReturnTime: 0.10s

shoot_sound:ROOT:sounds\autoCannon_fire_3.wav
shoot_sound_vol:0.20
shoot_flame:small
shoot_light:#FFccCCEE

canShoot: true

[projectile_1]
directDamage: 12
life: 60
speed: 7

frame: 5

drawSize: 0.6

explodeEffect:CUSTOM:bullet_hit

[movement]
movementType: LAND
moveSpeed: 0.9
moveAccelerationSpeed: 0.3
moveDecelerationSpeed: 0.2

maxTurnSpeed: 10.0
turnAcceleration: 2.0

moveSlidingMode :true
moveIgnoringBody:true


[canBuild_1]
name: mine
pos: 1
[canBuild_2]
name: heavy_mine
pos: 2
[canBuild_3]
name: barracks_t2,demoCharge,bunker,pillbox,heavy_howitzer,air_mine
pos: 0.1

[canBuild_4]
name: barracks,trench_horizontal,trench_vertical,foxhole, howitzer,tankTrap
pos: 0.2 