
[core]
name: fg_strider
class: CustomUnitMetadata
price: 1600
mass: 8000
maxHp: 800
maxShield: 200
shieldRegen: 0.15
shieldDeflectionDisplayRate: 1
shieldDisplayOnlyDeflection: true
shieldRenderRadius: 15

displayText: Fulgorian Strider
displayDescription:- Can transport 4 medium sized units\n- Transported units can shoot but not rotate\n- Can tag enemies for transported units to focus on\n- Can walk over any terrain
techLevel: 2
buildSpeed: 20s

#transportUnitsRequireTag:size1,size2
transportUnitsCanUnloadUnits: true
maxTransportingUnits: 4
transportUnitsKillOnDeath: false
transportUnitsRequireMovementType: LAND,OVER_CLIFF,HOVER

radius: 30
softCollisionOnAll: 24

[graphics]

image:        fg_strider.png
image_wreak:  fg_strider_dead.png
image_turret: ROOT:shared/graphics/blank.png
scaleImagesTo: 54
#scaleTurretImagesTo: 7
teamColorsOnTurret: true

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1

[attack]
turretRotateWithBody: true

canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

isFixedFiring: true
disablePassiveTargeting: true
aimOffsetSpread: 0

turretSize: 15
turretTurnSpeed: 0.8
maxAttackRange: 240

[turret_1]
x: 0
y: 0
barrelY: 10
idleDir:0
projectile: 1
delay: 0.2s

[projectile_1]
directDamage: 0
deflectionPower: -1
life: 15
instant: true
instantReuseLast: true
beamImage: targetPointer.png
beamImageEnd: targetMark.png
moveWithParent: true
explodeEffect: NONE
explodeEffectOnShield: NONE
color: #d4e4f2
alwaysVisibleInFog:true


[attachment_1pas]
x:-14
y:18
prioritizeParentsMainTarget: true
lockRotation: true
addTransportedUnits:true
canAttack:true
setDrawLayerOnTop:true
isUnselectable:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
smoothlyBlendPositionWhenExistingUnitAdded:false

idleDir:0

[attachment_2pas]
@copyFromSection: attachment_1pas
x: 14
idleDir:0

[attachment_4pas]
@copyFromSection: attachment_1pas
x:14
y:-18
idleDir:180

[attachment_3pas]
@copyFromSection: attachment_1pas
y: -18
idleDir:180


[leg_1]
x: -20
y: 15
attach_x: 5
attach_y: 0
moveSpeed: 2.2
heightSpeed: 1
moveWarmUp:4
resetAngle: 30
dust_effect: false
holdDisMin: 12
holdDisMax: 25
holdDisMin_maxMovingLegs: 4
estimatingPositionMultiplier: 1.4
image_leg: fg_strider_leg.png
image_foot: fg_strider_foot.png
image_foot_shadow: SHADOW:fg_strider_foot.png
draw_foot_on_top: false
favourOppositeSideNeighbours: true

[leg_2]
@copyFromSection: leg_1
x: 20
y: 15
attach_x: 5
attach_y: 0
[leg_3]
@copyFromSection: leg_1
x: -20
y: -15
attach_x: -5
attach_y: 0

[leg_4]
@copyFromSection: leg_1
x: 20
y: -15
attach_x: -5
attach_y: 0


[movement]
movementType: AIR
moveSpeed: 0.9
moveAccelerationSpeed: 0.02
moveDecelerationSpeed: 0.02

#reverseSpeedPercentage: 1
targetHeight: 0
targetHeightDrift: 0
startingHeightOffset: 0

maxTurnSpeed: 3
turnAcceleration: 0.08

moveSlidingMode: true
moveIgnoringBody: true
moveSlidingDir: 181

[ai]
useAsTransport:true

