
[core]


name: trebuchet

displayText: Trebuchet SPSA
displayDescription: -Self propelled siege artillery piece "Trebuchet"\n-Effective against buildings\n-Needs to ramp up it's cannons and autoloader before having maximum firerate\n-long range\n-Land attack \n-The final solution against porcupines

tags:big

class: CustomUnitMetadata
price: credits=10000,thorium=800
maxHp: 3000
mass: 18000
armour:4
transportSlotsNeeded:4

fogOfWarSightRange: 24

techLevel: 3
buildSpeed: 40s
#availableInDemo: true

radius: 30
displayRadius: 30

isBio: false

@memory gun1:number

[graphics]
total_frames: 4

image:        trebuchet.png
image_wreak:  trebuchet_wreck.png
image_turret: trebuchet_turret.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 0
animation_moving_end: 3
animation_moving_speed: 5

teamColorsOnTurret:true

dustEffect: true

[hiddenAction_retreat]
autoTrigger: if self.isControlledByAi() and self.hp(lessThan=550) and not self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
temporarilyAddTags: retreat

[hiddenAction_retreating]
autoTrigger: if self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
allowMultipleInQueue:false

[hiddenAction_active]
autoTrigger: if self.tags(includes='retreat') and (self.hp() == self.maxHp())
temporarilyRemoveTags: retreat

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
turretMultiTargeting: true
turretSize: 20
turretTurnSpeed: 0.5

aimOffsetSpread:0

maxAttackRange: 460
shootDelay: 600


[turret_2]
#
x: 0
y: 11
projectile: 1

attachedTo:1
slave:true

barrelY:30

turnSpeed:3
turnSpeedAcceleration: 1.0

warmup:2400

warmupCallDownRate:2

warmupShootDelayTransfer:550

warmupNoReset:true


shoot_sound:ROOT:sounds\brummbar_fire.wav
shoot_sound_vol:0.2
shoot_flame:medium
shoot_light:#FFEEEEEE

invisible:true
#image:trebuchet_turret_barrel.png

canShoot: true

recoilOffset: -5
recoilOutTime: 20
recoilReturnTime: 30

onShoot_triggerActions:turretSpin

[hiddenAction_turretSpin]
setUnitMemory:gun1 = 3

[hiddenAction_animGunDrain]
autoTrigger:true
#this drains the memory
setUnitMemory: gun1 = select(memory.gun1 > 0, memory.gun1 - 1, memory.gun1)

[decal_gun1]
basePositionFromTurret:2
total_frames:2
image:trebuchet_turret_barrel.png
teamColors: true

frame:select(memory.gun1 > 0 and memory.gun1 < 2, 1, 0)
isVisible: if self.hp > 0

layer:afterBody
imageScaleY:1.0
imageScaleX:1.0

[turret_1]
x: 0
y: 0
projectile: 1
canShoot:false


[projectile_1]
areaDamage: 200
areaRadius:100
buildingDamageMultiplier:3

targetGround:true

life: 300
speed: 2.0
targetSpeed:5.0
targetSpeedAcceleration:0.04
speedSpread:1

largeHitEffect: true

lightColor: #ffe92b
lightSize: 0.4

color:#e8bb27
frame:7

lightCastOnGround: true

#ballistic:True
#ballistic_delaymove_height:10
ballistic_height:80
initialUnguidedSpeedHeight: 5.0
gravity:3.50

targetGroundSpread:40

drawSize: 1.2


[movement]
movementType: LAND
moveSpeed: 0.45
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.2
reverseSpeedPercentage:0.9

maxTurnSpeed: 1.5
turnAcceleration: 0.3

moveSlidingMode :false
moveIgnoringBody:false





