
[core]

name: hwacha

displayText: Hwacha RA
displayDescription: -Light rocket artillery "Hwacha"\n-Extra building damage\n-armed with medium range ground to ground rockets to employ saturation bombing on the enemy positions\n-ground attack\n-ARTILJERIJA bosanac sam bekrija


class: CustomUnitMetadata
price: 1700
maxHp: 500
mass: 3000
armour:1


energyMax:8
energyRegen:0.01
energyNeedsToRechargeToFull:true
energyRegenWhenRecharging:0.025

techLevel: 2
buildSpeed: 22s
#availableInDemo: true
fogOfWarSightRange: 20
radius: 24
displayRadius: 24

isBio: false
softCollisionOnAll: 0

[graphics]
#The sprite was made with help of "Random"
total_frames: 2

imageScale:1.10

teamColorsOnTurret: true
image:        hwacha.png
image_wreak:  hwacha_wreck.png
image_turret: hwacha_turret.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 1


dustEffect: true

[hiddenAction_retreat]
autoTrigger: if self.isControlledByAi() and self.hp(lessThan=200) and not self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
temporarilyAddTags: retreat

[hiddenAction_retreating]
autoTrigger: if self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
allowMultipleInQueue:false

[hiddenAction_active]
autoTrigger: if self.tags(includes='retreat') and (self.hp() == self.maxHp())
temporarilyRemoveTags: retreat

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 10
turretTurnSpeed: 5


maxAttackRange: 280
shootDelay: 12

[turret_2]
x: 0
y: 0
projectile:2
barrelX:-9
barrelOffsetX_onOddShots:19
energyUsage:1
canAttackFlyingUnits:false
canAttackMaxAngle:15

shoot_sound:ROOT:sounds\missile_fire_1.wav
shoot_sound_vol:0.20
shoot_flame:small
shoot_light:#FFccCCEE


[projectile_2]
targetGround:true
areaDamage:50
areaRadius:60

wobbleAmplitude:1.2
wobbleFrequency:0.5
speedSpread:0.2
targetGroundSpread:10

buildingDamageMultiplier:1.5

drawSize: 1

image: ROOT:shared\graphics\tiny_missile.png
life: 120
color:#ff5743
speed: 1
targetSpeedAcceleration:0.10
targetSpeed: 8

trailEffect: true
largeHitEffect: true
ballistic: true
ballistic_delaymove_height:0
ballistic_height: 4


[movement]
movementType: LAND
moveSpeed: 1.00
moveAccelerationSpeed: 0.4
moveDecelerationSpeed: 0.5
reverseSpeedPercentage:0.7

maxTurnSpeed: 4.0
turnAcceleration: 0.95

moveSlidingMode :false
moveIgnoringBody:false

[ai]
buildPriority:0.7