[core]

name: aries_cover
copyFrom:ROOT:Templates\customEffects.template

class: CustomUnitMetadata
price: credits=6500, thorium=500
maxHp: 6000
mass: 80000

techLevel: 1
buildSpeed: 17s
#availableInDemo: true

radius: 22
displayRadius: 22

isBio: false
isUnselectable:true
isUnselectableAsTarget:true
canNotBeDamaged:true
canNotBeDirectlyAttacked:true
showInEditor:false
showOnMinimap:false

[graphics]
total_frames: 1
drawLayer:top
image:        aries_cover.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1

teamColorsOnTurret:true

dustEffect: true

[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
turretMultiTargeting: true
turretSize: 20
turretTurnSpeed: 4

maxAttackRange: 200
shootDelay: 10

[movement]
movementType: NONE
