
[core]
name: aries
class: CustomUnitMetadata

price: credits=9000,thorium=800

maxHp: 8000
armour:6
selfRegenRate:0.4

mass: 9000

techLevel: 2

displayText: HBT Aries
displayDescription: -Heavy bunker tank "Aries" \n-Can carry 12 infantry units\n-The infantry shoots out of the vehicle\n-can swim, but is slower in water\n-moderatly armed, heavily armoured, land attack and air attack\n-equipped with experimental regenerative plating based on oculian shield technology\n-If the enemy isn't coming to our bunker, our bunker will come to them!

displayText_ru: ТБТ "Ариес"\n-Может перевозить до 12 пехотинцев\n-Пехота стреляет из техники\n-может плавать, но медленней в воде\n-Относительно вооружен, тяжело бронированб воздушная и наземная атака\n-Экипирован экспериментальным регенеративным покрытием на базе технологий окулиан\n-Если враг не идёт к нашему бункеры, наш бункер едет к ним!
displayDescription_ru:

buildSpeed: 70s

radius: 46

isBio: false

maxTransportingUnits: 12

transportUnitsKillOnDeath: if self.isOverLiquid()
transportUnitsRequireMovementType: LAND,OVER_CLIFF
transportUnitsRequireTag:infantry
exit_x:0
exit_y:50
transportUnitsUnloadDelayBetweenEachUnit:15
exit_dirOffset:0
exit_moveAwayAmount:40



[graphics]
total_frames: 5
drawLayer:bottom

image:        aries.png
image_wreak:  aries_wreck.png
image_turret: aries_turret_base.png

image_shadow: AUTO
shadowOffsetX:3
shadowOffsetY:3

animation_moving_start: 1
animation_moving_end: 4
animation_moving_speed: 2

splastEffect: true
dustEffect: true

[attachment_gun]
x: 0
y: 0
onCreateSpawnUnitOf: aries_turret
isUnselectable: true
deattachIfWantingToMove: false
rotateWithParent: true
resetRotationWhenNotAttacking: true
prioritizeParentsMainTarget: true
canBeAttackedAndDamaged:false
setDrawLayerOnTop:true

[attachment_cover]
x: 0
y: 0
onCreateSpawnUnitOf: aries_cover
isUnselectable: true
deattachIfWantingToMove: false
rotateWithParent: true
resetRotationWhenNotAttacking: true
canBeAttackedAndDamaged:false
setDrawLayerOnTop:true
keepAliveWhenParentDies:false

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 15
turretTurnSpeed: 2
maxAttackRange: 500
shootDelay: 15
turretMultiTargeting: true


[turret_dummy]
x: 0
y: 0
canShoot: true
invisible:true
projectile:dummy

[projectile_dummy]
life: 1

directDamage: 0
areaDamage: 0
areaRadius: 0

speed: 1
instant: false

invisible: true
hitSound: false
explodeEffect: NONE
explodeEffectOnShield: NONE
trailEffect: false
largeHitEffect: false

[projectile_1]
directDamage: 30
areaDamage: 30
areaRadius: 30
life: 60
speed: 8

image: ROOT:shared/graphics/shell.png
drawSize: 0.55
color:#fba936
lightColor: #ff8600
lightSize: 0.2

[movement]
movementType: HOVER
moveSpeed: 0.9
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.09
reverseSpeedPercentage:0.9

maxTurnSpeed: 1.8


moveSlidingMode :false
moveIgnoringBody:false
targetHeight:0

[hiddenAction_movementOnWater]
autoTrigger: if self.overWater()
setUnitStats: moveSpeed = 0.5

[hiddenAction_movementOutOfWater]
autoTrigger: if not self.overWater()
setUnitStats: moveSpeed = 0.9

[attachment_1pas]
x:0
y:20
addTransportedUnits:true
canAttack:true
#setDrawLayerOnBottom:true
isUnselectable:true
canBeAttackedAndDamaged:false
resetRotationWhenNotAttacking:true
smoothlyBlendPositionWhenExistingUnitAdded:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true

[attachment_2pas]
@copyFromSection: attachment_1pas
x:0
y:-20
idleDir:-180

[attachment_3pas]
@copyFromSection: attachment_1pas
x:-12
y:0
idleDir:-90

[attachment_4pas]
@copyFromSection: attachment_1pas
x:12
y:0
idleDir:90

[attachment_5pas]
@copyFromSection: attachment_1pas
x:-21
y:15
idleDir:-45

[attachment_6pas]
@copyFromSection: attachment_1pas
x:21
y:15
idleDir:45

[attachment_7pas]
@copyFromSection: attachment_1pas
x:21
y:-15
idleDir:-315

[attachment_8pas]
@copyFromSection: attachment_1pas
x:-21
y:-15
idleDir:315

[attachment_9pas]
@copyFromSection: attachment_1pas
x:-12
y:34

[attachment_10pas]
@copyFromSection: attachment_1pas
x:12
y:34

[attachment_11pas]
@copyFromSection: attachment_1pas
x:-12
y:-34
idleDir:225

[attachment_12pas]
@copyFromSection: attachment_1pas
x:12
y:-34
idleDir:135




