
[core]
name: mn_tank
class: CustomUnitMetadata
price: 400
maxHp: 200
mass: 3000

displayText: Novarian Tank
displayDescription:- An invader from the cosmos!\n- Fires simple gun at ground target\n- Will upgrade itself after 5 kills\n- More will come...
techLevel: 1
buildSpeed: 8.6s

showInEditor: false
#availableInDemo: false

radius: 14
#displayRadius: 11
softCollisionOnAll: 24
fogOfWarSightRange: 20


[graphics]
total_frames: 4	

image:        mn_tank.png
image_wreak:  mn_tank_dead.png
image_turret: mn_tank_turret.png
teamColorsOnTurret:true
scaleImagesTo: 22
scaleTurretImagesTo: 14

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1

animation_moving_start: 0
animation_moving_end: 3
animation_moving_speed: 2

[hiddenAction_evolve]
autoTrigger: if self.kills(greaterThan=4)
convertTo: mn_tank_evo
buildSpeed: 2s

[attack]

canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 5
turretTurnSpeed: 10
maxAttackRange: 150
shootDelay: 25

[turret_1]
x: 0
y: 0
shoot_sound:plasma_fire
shoot_sound_vol:0.1
shoot_light: #e5f056
projectile: 1

recoilOffset: -1
recoilOutTime: 2
recoilReturnTime: 15

[projectile_1]
directDamage: 40
life: 150
speed: 8

frame: 5
drawSize: 0.6
lightColor: #e5f056

explodeEffect: CUSTOM:hitLightFlash

[effect_hitLightFlash]
priority: high
image: SHARED:light_50.png
life: 17
fadeOut: true
attachedToUnit: false
color: #e5f056
scaleFrom: 0.8
scaleTo: 0.8
alpha: 0.6
drawUnderUnits: false

[movement]
movementType: LAND
moveSpeed: 1
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.03

reverseSpeedPercentage:0.8

maxTurnSpeed: 3.6
turnAcceleration: 0.2

moveSlidingMode :true
moveIgnoringBody:false
moveSlidingDir:  181



