
[core]
name: mn_tank_evo
class: CustomUnitMetadata
price: 400
maxHp: 400
maxShield: 50
shieldRegen: 0.2
shieldDeflectionDisplayRate: 1
shieldDisplayOnlyDeflection: true
shieldRenderRadius: 15
mass: 3000

displayText: Novarian Tank (Evo)
displayDescription:- An evolved Novarian Tank\n- Now fires a metanova beam at longer range
techLevel: 1
buildSpeed: 8.6s

showInEditor: false
#availableInDemo: false

radius: 16
#displayRadius: 11
softCollisionOnAll: 24
fogOfWarSightRange: 20


[graphics]
total_frames: 4	

image:        mn_tank.png
image_wreak:  mn_tank_dead.png
image_turret: mn_tank_turret_evo.png
teamColorsOnTurret:true
scaleImagesTo: 26
scaleTurretImagesTo: 31

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1

animation_moving_start: 0
animation_moving_end: 3
animation_moving_speed: 2

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 5
turretTurnSpeed: 8
maxAttackRange: 180
shootDelay: 25

[turret_1]
x: 0
y: 0
shoot_sound:plasma_fire
shoot_sound_vol:0.1
shoot_light: #e5f056
projectile: 1

recoilOffset: -1
recoilOutTime: 2
recoilReturnTime: 15

[projectile_1]
directDamage: 80
deflectionPower: -1
life: 4
instant: true
instantReuseLast: true
beamImage: SHARED:beam3.png
beamImageEnd: SHARED:beam1_end.png
drawSize: 0.1
moveWithParent: true
color: #e5f056

[movement]
movementType: LAND
moveSpeed: 1
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.03

reverseSpeedPercentage:0.8

maxTurnSpeed: 3.6
turnAcceleration: 0.2

moveSlidingMode :true
moveIgnoringBody:false
moveSlidingDir:  181



