
[core]
name: fg_sweeper
class: CustomUnitMetadata
price: 1800
maxHp: 250
mass: 4000
maxShield: 800
shieldRegen: 0.20
shieldDeflectionDisplayRate: 1
shieldDisplayOnlyDeflection: true
shieldRenderRadius: 24

displayText: Fulgorian Sweeper
displayDescription: - A T2 crowd control hover unit\n- Equipped with a shotgun that targets ground

techLevel: 2

buildSpeed: 15s
availableInDemo: true

radius: 22
displayRadius: 22

[graphics]
total_frames: 1

image:        fg_sweep.png
image_wreak:  fg_sweep_dead.png
image_turret: fg_shotgun2.png
scaleImagesTo: 30
scaleTurretImagesTo: 15
teamColorsOnTurret:true

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
dustEffect: true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
maxAttackRange: 150
shootDelay: 40

[turret_1]
x: 0
y: -5
idleDir:0
projectile: 1
turnSpeed: 5
barrelY: 30

shoot_sound:tank_firing
shoot_sound_vol:0.5
shoot_flame: CUSTOM:sparks2*3
shoot_light: #FFcceeee

recoilOffset: -2.5
recoilOutTime: 4
recoilReturnTime: 20

[projectile_1]
#spawnUnit: fg_chainBeam(spawnChance=0.1)
spawnProjectilesOnCreate: 1*8(recursionLimit=1, maxSpawnLimit=8, offsetRandomDir=30)
areaDamage: 10
areaRadius: 50
shieldDamageMultiplier: 1
areaDamageNoFalloff: true
life: 150
speed: 15

image: fg_proj6.png
drawSize: 0.75

largeHitEffect: true
targetGround: true
targetGroundSpread: 30

lightColor: #ccffff
lightSize: 0.5

explodeEffect: CUSTOM:lightningShock, CUSTOM:sparks*8
explodeEffectOnShield: CUSTOM:lightningShock*1, CUSTOM:hitLightFlash


[movement]
movementType: HOVER
targetHeight: 2
targetHeightDrift: 1
moveSpeed: 1.2
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.07
maxTurnSpeed: 1.5
turnAcceleration: 1
moveSlidingMode :true
moveIgnoringBody:true

[effect_sparks]
attachedToUnit: false
life: 150
physics: true
xSpeedRelativeRandom: 1.6
ySpeedRelativeRandom: 1.6
hSpeed: 2
image: SHARED:spark.png
priority: verylow

[effect_sparks2]
attachedToUnit: false
life: 150
physics: true
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.5
hSpeed: 1
image: SHARED:spark.png
priority: verylow

[effect_hitLightFlash]
priority: high
image: SHARED:light_50.png
life: 17
fadeOut: true
attachedToUnit: false
color: #63e6e8
scaleFrom: 1.8
scaleTo: 1.8
alpha: 0.6
drawUnderUnits: false

[effect_lightningShock]
life: 60
hOffset: 0
dirOffset: 0
fadeInTime: 0
fadeOut: false
attachedToUnit: true
image: SHARED:lightning_shock.png
scaleFrom: 0.8
scaleTo: 0.8
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5

