[core]
name: mason
class: CustomUnitMetadata
price: 2000
maxHp: 1000
mass: 2000
armour:2

canRepairBuildings: true
canRepairUnits : true

#-temporarily disabled
#canRepairUnitsOnlyWithTags:repairable

selfRegenRate:0.05

displayText:Mason EV
displayDescription: -Dominion's engineering vehicle "Mason" \n-can quickly repair other units, and has self repair\n-armed with a light machinegun \n-capable of swimming \n-builds most types of factories and utility buildings

displayText_ru: Каменьщик ИМ
displayDescription_ru:-Инжинерная машина доминиона "Каменьщик"\n-Может быстро ремонтировать другую технику и способен к саморемонту\n-Вооружен лёгким пулемётом\n-Может плавать\n-Строит большинство заводов и прочие строения

techLevel: 2

buildSpeed: 30s
availableInDemo: true

radius: 15
displayRadius: 15

canReclaimResources: true
nanoRange: 150
nanoRepairSpeed:1.5
nanoBuildSpeed: 6.5

fogOfWarSightRange: 15

autoRepair: true
isBio: false
isBuilder: true

[graphics]

total_frames: 2

image:       mason.png
image_wreak:  mason_wreck.png
image_turret: mason_turret.png
teamColorsOnTurret:true

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 3


splastEffect: true

dustEffect: true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 16
turretTurnSpeed: 3

maxAttackRange: 200
turretMultiTargeting: true
shootDelay: 8

[turret_1]
#nano turret (nano must be slot 1)
x: 0
y: 0
warmup:10

canShoot: false
isMainNanoTurret:true

[turret_2]
x: 0
y: -6
projectile:1

image: mason_turret_1.png

attachedTo:1

recoilOffset: -1.5
recoilReturnTime: 0.10s

shoot_sound:ROOT:sounds\lmg_fire_1.wav
shoot_sound_vol:0.15
shoot_flame:small
shoot_light:#FFccCCEE

size:8

canShoot: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false


[projectile_1]
directDamage: 6
life: 60
speed: 8

frame: 5

drawSize: 0.6

[movement]
movementType: HOVER
moveSpeed: 1.0
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.08

maxTurnSpeed: 4.5
turnAcceleration: 2.5

moveSlidingMode :false
moveIgnoringBody:false

[hiddenAction_movementOnWater]
autoTrigger: if self.overWater()
setUnitStats: moveSpeed = 0.7

[hiddenAction_movementOutOfWater]
autoTrigger: if not self.overWater()
setUnitStats: moveSpeed = 1.0

[canBuild_4]
name: light_veh_fac,light_veh_fac_t2, tank_factory,tank_factory_t2, barracks,barracks_t2, domi_air_factory, domi_air_factory_t2
pos:  2
tech: 1

[canBuild_8]
name: repairStation,radar,wall
pos:  5

[canBuild_10]
name: dominion_turret,dominion_turret_t2,dominion_flame_turret_t1,dominion_lightning_turret_t1,
pos:  7

[canBuild_11]
name: dominion_aa_turret,dominion_aa_turret_t2
pos:  8

[canBuild_16]
name: dominion_extractor,dominion_extractor_t2,
pos:  1
tech: 1

[canBuild_18]
name: domi_fabricator,domi_fabricator_t2
pos:  9
tech: 1


[canBuild_17]
name: reclaim
pos:  -1

[ai]
useAsBuilder: true