
[core]
copyFrom:ROOT:Templates\customEffects.template
name: champion

displayText: Champion CV
displayDescription:-High-tech Combat Vehicle "Champion" \n-armed with a coil gun and missiles\n-ground attack

displayText_ru: Чемпион БМ
displayDescription_ru:-Высокотехнологичная боевая машина "Чемпион"\n-Вооружен гаусс пушкой и ракетницой\n-Наземная атака

class: CustomUnitMetadata
price: credits=2000, thorium=120
maxHp: 900
mass: 3500
armour:3

techLevel: 3
buildSpeed: 25s
#availableInDemo: true

radius: 22
displayRadius: 22

isBio: false
softCollisionOnAll: 0

[graphics]
total_frames: 2

teamColorsOnTurret: true
image:        champion.png
image_wreak:  champion_wreck.png
image_turret: champion_turret_base.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 1


dustEffect: true

[hiddenAction_retreat]
autoTrigger: if self.isControlledByAi() and self.hp(lessThan=200) and not self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
temporarilyAddTags: retreat

[hiddenAction_retreating]
autoTrigger: if self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
allowMultipleInQueue:false

[hiddenAction_active]
autoTrigger: if self.tags(includes='retreat') and (self.hp() == self.maxHp())
temporarilyRemoveTags: retreat

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 10
turretTurnSpeed: 5


maxAttackRange: 280
shootDelay: 15

[turret_3]
x:0
y:0

image:champion_turret_barrel.png

attachedTo:1
slave:true
projectile: 1

recoilOffset: -3
recoilReturnTime: 0.20s

aimOffsetSpread:0.2

turnSpeed: 3
barrelY: 18

canShoot: true

shoot_light:#00f2ff
shoot_sound:ROOT:sounds\coilgun_fire_2.wav
shoot_sound_vol:0.25
shoot_flame:CUSTOM:coilgun_fire_medium

canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

limitingRange:180

[turret_2]
image:champion_turret_missiles.png
attachedTo:1
slave:true

x: 9
y: 0
size:5

canAttackMaxAngle:30

projectile:2
delay:400
warmup:20

shoot_sound:missile_fire
shoot_sound_vol:0.6
shoot_flame:large
canOnlyAttackUnitsWithoutTags:missile

[turret_1]
x: 0
y: 0
projectile: 1
canShoot:false


[projectile_1]
directDamage: 40
areaDamage: 20
areaRadius: 20
life: 80
speed: 9

color: #59f7ff
lightColor: #74e9ff
lightSize: 0.5

image: ROOT:shared\graphics\coilgun_shot.png
drawSize: 0.5

[projectile_2]
areaDamage:150
areaRadius:60

wobbleAmplitude:2.2
wobbleFrequency:0.2
speedSpread:0.2
targetGroundSpread:15

drawSize: 1.1

image: ROOT:shared\graphics\tiny_missile.png
life: 150
color:#ff5743
speed: 2.25
targetSpeedAcceleration:0.3
targetSpeed: 6

trailEffect: true
trailEffectRate:2
largeHitEffect: true

[movement]
movementType: LAND
moveSpeed: 1.20
moveAccelerationSpeed: 0.3
moveDecelerationSpeed: 0.4
reverseSpeedPercentage:0.6

maxTurnSpeed: 5.0
turnAcceleration: 0.85

moveSlidingMode :false
moveIgnoringBody:false

[ai]
buildPriority:0.7