
[core]


name: sledgehammer

displayText: Sledgehammer tank
displayDescription: -Heavy tank "Sledgehammer" armed with a 380mm snub cannon\n-Big area damage, 15s reload, friendly fire\n-Shells are equipped with mini-nuclear warheads\n-Land attack\n-has light mg against ground and air\n-Kaboom? \n-Yes, Hans, kaboom.

displayText_ru: Танк Кувалда
displayDescription_ru: -Тяжелый танк "Кувалда" вооруженный короткоствольным 380мм орудием\n-Большой урон по области, 15с перезарядка, имеет огонь по своим\n-Снаряды имеют миниатюрные ядерные боеголовки\n-Наземная атака\n-Имеет пулемет против земли и воздуха\n-Бум ?\n-Да, Ганс, Бум.

copyFrom:ROOT:Templates\customEffects.template

tags:big

class: CustomUnitMetadata
price: credits=6500, thorium=500
maxHp: 6000
mass: 80000
armour:10
transportSlotsNeeded:2

fogOfWarSightRange: 12

techLevel: 3
buildSpeed: 50s
#availableInDemo: true

radius: 35
displayRadius: 40

isBio: false


[graphics]
total_frames: 4

image:        sledgehammer.png
image_wreak:  sledgehammer_wreck.png
image_turret: sledgehammer_turret_base.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 0
animation_moving_end: 3
animation_moving_speed: 5

teamColorsOnTurret:true

dustEffect: true

[hiddenAction_retreat]
autoTrigger: if self.isControlledByAi() and self.hp(lessThan=550) and not self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
temporarilyAddTags: retreat

[hiddenAction_retreating]
autoTrigger: if self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
allowMultipleInQueue:false

[hiddenAction_active]
autoTrigger: if self.tags(includes='retreat') and (self.hp() == self.maxHp())
temporarilyRemoveTags: retreat

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
turretMultiTargeting: true
turretSize: 20
turretTurnSpeed: 2

isFixedFiring: true

aimOffsetSpread:0

maxAttackRange: 270
shootDelay: 900

[turret_2]
#
x: 0
y: 0
attachedTo:1
projectile: 1

barrelY:20

turnSpeed:3
turnSpeedAcceleration: 1.0

warmup:30

canAttackMaxAngle:10

shoot_sound:ROOT:sounds\sturmtiger_fire_1.wav
shoot_sound_vol:0.5
shoot_flame:small
shoot_light:#FFEEEEEE

canShoot: true

image:sledgehammer_turret_barrel.png

recoilOffset: -8
recoilOutTime: 30
recoilReturnTime: 600

canAttackFlyingUnits: false
canAttackLandUnits:   true
[turret_1]
x: 0
y: 0
projectile: 1

canShoot:false

[turret_1]
x: 0
y: 0
projectile: dummy
delay:600
canShoot:true
limitingRange:205

[projectile_1]
areaDamage: 900
areaRadius: 140

targetGround:true

life: 200
speed: 4.5


largeHitEffect: true

lightColor: #ffe92b
lightSize: 1.0

color:#e8bb27
image: ROOT:shared\graphics\howitser_shell.png

friendlyFire:true

initialUnguidedSpeedHeight: 0.5
gravity:0.1
lightCastOnGround: true

targetGroundSpread:15

drawSize: 1.5
nukeWeapon:true
areaExpandTime:60
spawnProjectilesOnExplode:2
explodeOnEndOfLife:true

[projectile_dummy]
life: 1

directDamage: 0
areaDamage: 0
areaRadius: 0

speed: 1
instant: false

invisible: true
hitSound: false
explodeEffect: NONE
explodeEffectOnShield: NONE
trailEffect: false
largeHitEffect: false

[projectile_2]
areaDamage: 0
areaRadius: 0

targetGround:true

life: 1
speed: 0
explodeEffect:bigBoom
explodeOnEndOfLife:true
[attachment_mg]
x: -5.5
y: 6.5
onCreateSpawnUnitOf: sledgehammer_mg
isUnselectable: true
deattachIfWantingToMove: false
rotateWithParent: true
resetRotationWhenNotAttacking: true
prioritizeParentsMainTarget: true
canBeAttackedAndDamaged:false
setDrawLayerOnTop:true
[movement]
movementType: LAND
moveSpeed: 0.5
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.15
reverseSpeedPercentage:0.9

maxTurnSpeed: 1.5
turnAcceleration: 0.3

moveSlidingMode :false
moveIgnoringBody:false





