[core]

name: sledgehammer_mg
copyFrom:ROOT:Templates\customEffects.template

class: CustomUnitMetadata
price: credits=6500, thorium=500
maxHp: 6000
mass: 80000
armour:10
transportSlotsNeeded:2

fogOfWarSightRange: 12

techLevel: 1
buildSpeed: 17s
#availableInDemo: true

radius: 22
displayRadius: 22

isBio: false
isUnselectable:true
isUnselectableAsTarget:true
canNotBeDamaged:true
canNotBeDirectlyAttacked:true
showInEditor:false
showOnMinimap:false
[graphics]
total_frames: 4

image:        ROOT:shared/graphics/blank.png
image_turret: sledgehammer_turret_2.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 0
animation_moving_end: 3
animation_moving_speed: 5

teamColorsOnTurret:true

dustEffect: true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
turretMultiTargeting: true
turretSize: 20
turretTurnSpeed: 4

maxAttackRange: 200
shootDelay: 10

[turret_3]
#
x:0
y:0
projectile: 2

canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
delay:18
size:10

turnSpeed:4

recoilOffset: -1.5
recoilReturnTime: 0.15s

shoot_sound:ROOT:sounds\autoCannon_fire_1.wav
shoot_sound_vol:0.2
shoot_flame:small
shoot_light:#FFccCCEE

canShoot: true

limitingRange:200

[projectile_2]
directDamage: 16
life: 80
speed: 8

frame: 5

drawSize: 0.8

explodeEffect:CUSTOM:bullet_hit

[movement]
movementType: NONE
