
[core]

name: praetorian

displayText: Praetorian MBT
displayDescription: -High Tech MBT of Dominion\n-Upgrade from the praetorian, manned with the best crew and tech available\n-has a top autocannon against personell and light aircraft\n-has a small thorium fusion reactor to power it's Coil cannon

copyFrom:ROOT:Templates\customEffects.template

class: CustomUnitMetadata
price: credits=3200, thorium=220
maxHp: 2500
armour:7
mass: 5000
techLevel:3
buildSpeed: 35s
#availableInDemo: true

transportSlotsNeeded:2
radius: 21
displayRadius: 22

isBio: false
softCollisionOnAll: 0

[graphics]
total_frames: 4

teamColorsOnTurret: true
image:        praetorian.png
image_wreak:  praetorian_wreck.png
image_turret: praetorian_turret_base.png

image_shadow: AUTO
shadowOffsetX:2.5
shadowOffsetY:2.5


animation_moving_start: 0
animation_moving_end: 3
animation_moving_speed: 2


dustEffect: true

[hiddenAction_retreat]
autoTrigger: if self.isControlledByAi() and self.hp(lessThan=500) and not self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
temporarilyAddTags: retreat

[hiddenAction_retreating]
autoTrigger: if self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
allowMultipleInQueue:false

[hiddenAction_active]
autoTrigger: if self.tags(includes='retreat') and (self.hp() == self.maxHp())
temporarilyRemoveTags: retreat

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 15
turretTurnSpeed: 3


maxAttackRange: 200
shootDelay: 130

[turret_2]
#
x: 0
y: 12
image:praetorian_turret_barrel.png
attachedTo:1
slave:true
 #invisible:true
projectile: 1

recoilOffset: -4
recoilReturnTime: 1.00s

turnSpeed: 3
barrelY: 20

canShoot: true

shoot_sound:ROOT:sounds\tank_fire_3.wav
shoot_sound_vol:0.250
shoot_flame:medium

canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
warmup:10

[turret_1]
x: 0
y: -2
projectile: 1
canShoot:false

canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

 #invisible:true

[turret_3]
#
x:4
y:-5
image:praetorian_turret_2.png
attachedTo:1
#slave:true
projectile: 2

canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
delay:18
size:10

turnSpeed:4

recoilOffset: -1.5
recoilReturnTime: 0.15s

shoot_sound:ROOT:sounds\autoCannon_fire_1.wav
shoot_sound_vol:0.2
shoot_flame:small
shoot_light:#FFccCCEE

canShoot: true


[projectile_2]
directDamage: 16
life: 80
speed: 8

frame: 5

drawSize: 0.8

explodeEffect:CUSTOM:bullet_hit

[projectile_1]
directDamage: 300
areaDamage: 50
areaRadius: 40
life: 60
speed: 7

frame: 1
drawSize: 1.2


[movement]
movementType: LAND
moveSpeed: 0.85
moveAccelerationSpeed: 0.30
moveDecelerationSpeed: 0.40
reverseSpeedPercentage:0.9

maxTurnSpeed: 4.0
turnAcceleration: 0.75

moveSlidingMode :false
moveIgnoringBody:false

[ai]
buildPriority:0.7