
[core]
name: bunker
class: CustomUnitMetadata
price: 1000
maxHp: 2700
armour:7
mass: 2000

techLevel: 2
transportUnitsKillOnDeath:false
displayText: Bunker
displayDescription: -A concrete building to give cower to your soldiers

transportUnitsUnloadDelayBetweenEachUnit:20

buildSpeed: 30s

#footprint used for collisions with units (left, up, right, down)
footprint: -1,-1,1,1

buildingToFootprintOffsetX:10
buildingToFootprintOffsetY:10
#used for placement, and placement of other buildings
constructionFootprint: -1,-1,1,1

radius: 50
isBuilding:true
isBio: false

maxTransportingUnits: 8
transportUnitsRequireTag:infantry
transportUnitsRequireMovementType: LAND,OVER_CLIFF,HOVER

exit_x:0
exit_y:14

exit_dirOffset:90
exit_moveAwayAmount:30

[decal_1]
image:bunker.png
basePositionFromTurret:1
layer:onTop
teamColors:true

[graphics]
image:        blank.png
image_back:   bunker_bottom.png
image_wreak:  NONE
image_turret: NONE
image_shadow: AUTO
shadowOffsetX:3
shadowOffsetY:3
lock_shadow_rotation_with_main_turret:true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

maxAttackRange: 420
shootDelay:1200
turretTurnSpeed:1
isFixedFiring:true
turretRotateWithBody:false
turretMultiTargeting: true

[turret_1]
x:0
y:0
idleDir:-90
shouldResetTurret:false
invisible:true
canShoot:false
turnSpeed:10
size:30
projectile:dummy

[projectile_dummy]
life:100
areaDamage: 0
areaRadius:0
instant:true
targetGround:true
spawnUnit: warning
explodeOnEndOfLife:false
explodeEffect: NONE


[movement]
movementType: NONE

[attachment_1]
x:7
y:25
addTransportedUnits:true
canAttack:true

setDrawLayerOnTop:false

isUnselectable:true
canBeAttackedAndDamaged:false
resetRotationWhenNotAttacking:true
smoothlyBlendPositionWhenExistingUnitAdded:true
keepAliveWhenParentDies:true
rotateWithParent:true

[attachment_2]
@copyFromSection: attachment_1
x:-7
y:25


[attachment_3]
@copyFromSection: attachment_1
x:19
y:19

[attachment_4]
@copyFromSection: attachment_1
x:-19
y:19


[attachment_5]
@copyFromSection: attachment_1
x:10
y:6

[attachment_6]
@copyFromSection: attachment_1
x:-10
y:6

[attachment_7]
@copyFromSection: attachment_1
x:22
y:3

[attachment_8]
@copyFromSection: attachment_1
x:-22
y:3

[ai]
lowPriorityTargetForOtherUnits:true