
[core]

name: komodo

displayText: Komodo AA
displayDescription: -Anti air vehicle "Komodo"\n-Armed with a 12 slots missile battery\n-air attack


class: CustomUnitMetadata
price: 2000
maxHp: 1000
armour:2
mass: 2400

techLevel: 2
buildSpeed: 27s
#availableInDemo: true

fogOfWarSightRange: 20

radius: 18
displayRadius: 18

energyMax:11
energyRegen:0.015
energyNeedsToRechargeToFull:true
energyRegenWhenRecharging:0.05

isBio: false
softCollisionOnAll: 0

[graphics]
total_frames: 2

teamColorsOnTurret: true
image:        komodo.png
image_wreak:  komodo_wreck.png
image_turret: komodo_turret.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 1


dustEffect: true

[hiddenAction_retreat]
autoTrigger: if self.isControlledByAi() and self.hp(lessThan=250) and not self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
temporarilyAddTags: retreat

[hiddenAction_retreating]
autoTrigger: if self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
allowMultipleInQueue:false

[hiddenAction_active]
autoTrigger: if self.tags(includes='retreat') and (self.hp() == self.maxHp())
temporarilyRemoveTags: retreat

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 10
turretTurnSpeed: 7


maxAttackRange: 290
shootDelay: 10


[turret_1]
#
x: 0
y: -2

energyUsage:1
projectile: 1

turnSpeed: 7
barrelY: 15
shoot_sound:ROOT:sounds\missile_fire_1.wav
shoot_sound_vol:1.0
shoot_flame:small

canShoot: true

[projectile_1]
areaDamage: 80
areaRadius: 70

life: 240

speed: 4.5
targetSpeed: 18
targetSpeedAcceleration:0.1

trailEffect: true
largeHitEffect: true
lightColor:#ffa100
lightSize:1.0

wobbleAmplitude:1.2
wobbleFrequency:30
image: ROOT:shared\graphics\tiny_missile.png
color:#ffa100

autoTargetingOnDeadTarget: true

[movement]
movementType: LAND
moveSpeed: 1.2
moveAccelerationSpeed: 0.6
moveDecelerationSpeed: 0.7
reverseSpeedPercentage:0.7

maxTurnSpeed: 5.0
turnAcceleration: 0.85

moveSlidingMode :false
moveIgnoringBody:false

[ai]
buildPriority:0.4