
[core]
name: volt

displayText: Volt HoverTank
displayDescription: -Hover cushion tank "Volt" equipped with dual autocannons with emp payload \n-vastly increased damage to shield \n-reduced damage to buildings and hull \n-Land and Air attack

class: CustomUnitMetadata
price: 2600
maxHp: 1600
armour:4

mass: 3000

techLevel: 2
buildSpeed: 28.0s
#availableInDemo: true

radius: 28
displayRadius: 30

isBio: false
softCollisionOnAll: 0


[graphics]
total_frames: 2

teamColorsOnTurret: true
image:        volt.png
image_wreak:  volt_wreck.png
image_turret: volt_turret_base.png

image_shadow: AUTO
shadowOffsetX:2
shadowOffsetY:2


animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 3

animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3

splastEffect: true
dustEffect: true

[hiddenAction_kite]
autoTrigger: if self.isAttacking() and self.isControlledByAI() and self.numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=150)

clearAllWaypoints: true
addWaypoint_target_fromReference: createMarker(x=self.x, y=self.y, dir=direction(self.x, self.y, attacking.x, attacking.y)).getOffsetRelative(y=-60)
addWaypoint_type: move
allowMultipleInQueue: false

[hiddenAction_retreat]
autoTrigger: if self.isControlledByAi() and self.hp(lessThan=350) and not self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
temporarilyAddTags: retreat

[hiddenAction_retreating]
autoTrigger: if self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
allowMultipleInQueue:false

[hiddenAction_active]
autoTrigger: if self.tags(includes='retreat') and (self.hp() == self.maxHp())
temporarilyRemoveTags: retreat

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 12
turretTurnSpeed: 4

maxAttackRange: 230

shootDelay: 100

[turret_2]
#
image:volt_turret_barrel_l.png
x: -6
y: 10
attachedTo:1
slave:true

projectile: 1
warmup:10

recoilOffset: -5
recoilReturnTime: 0.30s

turnSpeed: 3
barrelY: 7

canShoot: true

shoot_sound:ROOT:sounds\empCannon_fire_1.wav
shoot_sound_vol:0.250
shoot_flame:small

chargeEffectImage: SHARED:lighting_charge.png

[effect_hitLightFlash]
priority:high

image: SHARED:light_50.png
life: 17
fadeOut: true
attachedToUnit: false
color: #63e6e8

scaleFrom: 1.8
scaleTo: 1.8
alpha: 0.6
drawUnderUnits:false


[effect_lightningShock]
life: 60


hOffset: 0
dirOffset: 0

fadeInTime: 0
fadeOut: false

attachedToUnit: true


image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5



[effect_sparks]
attachedToUnit: false
life: 150
physics: true
xSpeedRelativeRandom: 1.6
ySpeedRelativeRandom: 1.6
hSpeed: 2
image: SHARED:spark.png
priority: verylow

[turret_3]
#
image:volt_turret_barrel_r.png
copyFrom: 2
x: 6
y: 10
linkDelayWithTurret:2
warmup:20

[turret_1]
x: 0
y: -10
projectile: 1
canShoot:false


[projectile_1]
directDamage: 50
life: 100

speed:10

shieldDamageMultiplier: 3.0
shieldDefectionMultiplier:0.40

buildingDamageMultiplier: 0.6

drawSize:0.75
lightColor: #ccffff
lightSize: 0.8
color:#00c0ff
image: ROOT:shared\graphics\shell.png

[movement]
movementType: HOVER
moveSpeed: 0.9
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.04

targetHeight:3
reverseSpeedPercentage:0.5

maxTurnSpeed: 3.0
turnAcceleration: 0.6

moveSlidingMode :true
moveIgnoringBody:true





