#[code not made by me. I found this in the Rusted Warfare discord by searching "piercing projectile"]
#by: Paul! 
#p.s. credit me! [here ya go]
#Top secrete project
#-------------------


#parent spawn code 

#[projectile_sample]
#spawnUnit: Piercing Projectile(offsetDir=0)

#0r

#spawnUnit: Piercing Projectile(offsetDir=0), Piercing Projectile(offsetDir=0.5), Piercing Projectile(offsetDir=-0.5), Piercing Projectile(offsetDir=1), Piercing Projectile(offsetDir=-1), Piercing Projectile(offsetDir=-0.5), Piercing Projectile(offsetDir=1.5), Piercing Projectile(offsetDir=-1.5)

[core]

#cOPY
showInEditor: FALSE
name: Piercing Projectile
class: CustomUnitMetadata
price: 1
maxHp: 9999
mass: 9000
techLevel: 1
buildSpeed: 1
#availableInDemo: true
radius: 3
displayRadius: 10
fogOfWarSightRange: 1
isBio: false

#--------------------------------distance travel
energyMax:20
#--------------------------------


energyRegen: 0
transportSlotsNeeded: -1
#LIGHT IT U
#fireTurretXAtSelfOnDeath: 3
isUnselectable:true
canNotBeGivenOrdersByPlayer:true
disableAllUnitCollisions: true
canNotBeDirectlyAttacked:true
#createOnAggressiveTeam: true
dieOnZeroEnergy: true
explodeOnDeath: false
hideScorchMark: true
showOnMinimap: false
#================================
ignoreInUnitCapCalculation: true
#================================
#tags:

[hiddenAction_created]
autoTriggerOnEvent: created
alsoQueueAction:impact2 
[hiddenAction_impact]
autoTriggerOnEvent: teleported
alsoQueueAction:impact2 
[hiddenAction_impact2]
buildSpeed: 0.01s
fireTurretXAtGround: Dummy


#-------------------------------------------Teleport distance
fireTurretXAtGround_withOffset: 0,20
#-------------------------------------------


#fireTurretXAtGround_count: 2
addResources: energy=-1
[graphics]
total_frames: 1
image:        null.png
image_shadow: NONE
showHealthBar: false
showEnergyBar:false
showQueueBar: false
icon_zoomed_out_neverShow: true
[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false

maxAttackRange: 50
[turret_Dummy]
#dummy
x: 0
y: 0

invisible: true

projectile: 1
size: 0
shoot_sound:NONE
shoot_sound_vol:0
shoot_flame: NONE
canShoot: true

[projectile_1]

teleportSource: true

life: 5000
speed: 10
hitSound: true
	
targetGround:true
targetGroundSpread: 0
largeHitEffect: false
deflectionPower: 1

#-------------------------damage
areaDamage: 150
areaRadius: 30
#--------------------------
hullDamageMultiplier: 1
armourIgnoreAmount: 0
#------------------------------

pushForce: 1
pushVelocity: 0

lightSize: 0.5
lightColor: #ccffff
explodeEffect: NONE

image: fg_spike.png
drawSize: 0.7

trailEffect: CUSTOM:sparks*1, CUSTOM:projectileTrail
trailEffectRate: 0.5

lightColor: #ccffff
lightSize: 0.55

explodeEffect: NONE

lightCastOnGround: true

[effect_hitLightFlash]
priority: high
image: SHARED:light_50.png
life: 15
fadeOut: true
attachedToUnit: false
color: #ccffff
#color: #63e6e8
scaleFrom: 0.1
scaleTo: 0.1
alpha: 2
drawUnderUnits: false

[effect_sparks]
attachedToUnit: false
life: 60
physics: true
fadeOut: true
spawnChance: 0.5
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.5
hSpeed: 1
image: SHARED:spark.png
priority: verylow

[effect_light]
priority: high
image: SHARED:light_50.png
life: 15
fadeOut: true
attachedToUnit: false
color: #ccffff
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.6
drawUnderUnits: true

[effect_projectileTrail]
image: SHARED:light_50.png
life: 12
fadeOut: true
attachedToUnit: false
color: #ccffff
fadeInTime:2
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.4
drawUnderUnits:true
#ySpeedRelative:-1

[movement]
movementType: land