
[core]

name: varangian

displayText: Varangian Heavy Tank
displayDescription: -High tech Dominion heavy tank\n-extremelly slow and devastating\n-can produce t1 tanks\n-has a thorium reactor powering it's factory\n-Ground and weak air attack\n-Loyal till the very end

copyFrom:ROOT:Templates\customEffects.template

class: CustomUnitMetadata
price: credits=20000,thorium=2000
maxHp: 16000
armour:10
mass: 35000
techLevel:3
buildSpeed: 80s

nanoFactorySpeed: 3.00

radius: 40
displayRadius: 40

isBio: false
softCollisionOnAll: 0

canBuild_2_name: dominion_builder,legionaire,sagittarii,birdeater,pilum,thunder,mallet,shepherd
canBuild_2_pos:  1

exit_x:0
exit_y:30

exit_dirOffset:-180
exit_moveAwayAmount:50

[graphics]
total_frames: 4

teamColorsOnTurret: true
image:        legatus.png
image_wreak:  legatus_wreck.png
image_turret: legatus_turret_base.png



image_shadow: AUTO
shadowOffsetX:2.5
shadowOffsetY:2.5

animation_moving_start: 0
animation_moving_end: 3
animation_moving_speed: 2


dustEffect: true

[turret_4]
#
x:0
y:0
#image:
invisible:true
attachedTo:1
#slave:true
projectile: 2

canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
delay:10
size:10

turnSpeed:4

recoilOffset: -1.5
recoilReturnTime: 0.15s

shoot_sound:ROOT:sounds\autoCannon_fire_2.wav
shoot_sound_vol:0.2
shoot_flame:small
shoot_light:#FFccCCEE

canShoot: true

[projectile_2]
directDamage: 20
life: 80
speed: 8

frame: 5

drawSize: 0.8

explodeEffect:CUSTOM:bullet_hit

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 15
turretTurnSpeed: 2


maxAttackRange: 220
shootDelay: 170

[turret_2]
#
x: -9
y: 9
image:legatus_turret_barrel.png
attachedTo:1
slave:true
 #invisible:true
projectile: 1

recoilOffset: -8
recoilReturnTime: 2.50s

canAttackMaxAngle:10

barrelY: 28

canShoot: true

warmup:10

shoot_sound:ROOT:sounds\heavy_cannon_fire_2.wav
shoot_sound_vol:0.250
shoot_flame:large

canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

[turret_3]
x: 9
y: 9
copyFrom:2

linkDelayWithTurret:2
warmup:20
[turret_1]
x: 0
y: 2
projectile: 1
canShoot:false

canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

[projectile_1]
directDamage: 800
areaDamage: 100
areaRadius: 50
life: 60
speed: 10


lightColor: #fba936
lightSize: 0.55
image: ROOT:shared/graphics/shell.png
drawSize: 1
color:#fba936

[movement]
movementType: LAND
moveSpeed: 0.4
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.08
reverseSpeedPercentage:0.9

maxTurnSpeed: 1.5
turnAcceleration: 0.20

moveSlidingMode :false
moveIgnoringBody:false

[ai]
buildPriority:0.7