[core]
name: Tree
class: CustomUnitMetadata
price: 3112018
mass: 30000
maxHp: 30000
selfRegenRate: 0.2
armour: 20

energyMax: 50
energyNeedsToRechargeToFull:true
energyRegen:0.1
energyRegenWhenRecharging:0.1

displayText: Tree
displayDescription:- @tree03\n- The Tree guy himself, founder of the Treegang\n- "semoid extinction beam"\n- "also try :k=wilt"\n- "0==(========>"\n- :yoj:
techLevel: 3
buildSpeed: 10s
isBuilding: true

radius: 30
softCollisionOnAll: 24

[graphics]
image:        tree_pfp.png
image_wreak:  NONE
image_turret: NONE
scaleImagesTo: 120
#scaleTurretImagesTo: 24

image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1

[hiddenAction_replant]
autoTrigger: if self.customTimer(laterThanSeconds=120) and self.numberOfUnitsInTeam(withTag='smalltree', lessThan=20)
fireTurretXAtGround: seedler
fireTurretXAtGround_withTarget: self
resetCustomTimer: true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 15
turretMultiTargeting: true
maxAttackRange: 800
shootDelay: 10

[turret_1]
x: 0
y: 0
shoot_sound:shot_03.wav
shoot_sound_vol: 0.35
shoot_flame: CUSTOM:light
shoot_light: #04b004
energyUsage: 1
canAttackMaxAngle:30 
projectile: 1
size: 12

[turret_2]
x: -40
y: 0
copyFrom: 1
warmup: 0.1s

[turret_3]
x: 40
y: 11
copyFrom: 1
warmup: 0.2s

[turret_semoid]
x: 0
y: 0
shoot_sound:lazer.ogg
shoot_sound_vol: 1
shoot_flame: CUSTOM:light
shoot_light: #04b004
warmup: 5s
canAttackMaxAngle:30 
projectile: semoid
size: 12

[turret_seedler]
x: 0
y: 0
projectile: seed
canShoot: false
delay: 60s

[projectile_1]
life: 240
drawSize: 1
speed: 10
largeHitEffect: true

areaDamage: 100
areaRadius: 25
areaDamageNoFalloff: true

targetGround: true
targetGroundSpread: 15
targetGround_includeTargetHeight: true

lightColor: #04b004
lightSize: 0.2
explodeEffect: CUSTOM:hitLightFlash
explodeEffectOnShield: CUSTOM:hitLightFlash

[projectile_semoid]
areaDamage: 5000
areaRadius: 80
deflectionPower: -1
life: 80
instant: true
instantReuseLast: true
beamImage: SHARED:beam3.png
beamImageEnd: SHARED:beam1_end.png
drawSize: 3
moveWithParent: true
color: #04b004
largeHitEffect: true

[projectile_seed]
spawnProjectilesOnCreate: seed*1(recursionLimit=1, maxSpawnLimit=1, offsetRandomDir=360)
spawnUnit: Tree_small
life: 250
speed: 5
directDamage: 0
targetGround: true
targetGroundSpread: 200
lightColor: #04b004
lightSize: 0.1
explodeEffect: CUSTOM:hitLightFlash

[effect_hitLightFlash]
priority: high
image: SHARED:light_50.png
life: 15
fadeOut: true
attachedToUnit: false
color: #04b004
#color: #63e6e8
scaleFrom: 0.1
scaleTo: 0.1
alpha: 2
drawUnderUnits: false

[effect_light]
priority: high
image: SHARED:light_50.png
life: 15
fadeOut: true
attachedToUnit: false
color: #04b004
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.6
drawUnderUnits: true

[effect_warmup]
priority:high
image: SHARED:light_50.png
life: 25
fadeOut: true
attachedToUnit: true
color: #04b004
scaleFrom: 0.1
scaleTo: 0.1
alpha: 0.8
drawUnderUnits:false
ySpeedRelative:3.9

[effect_projectileTrail]
image: SHARED:light_50.png
life: 20
fadeOut: true
attachedToUnit: false
color: #04b004
fadeInTime:2
scaleFrom: 0.4
scaleTo: 0.4
alpha: 0.6
drawUnderUnits:true
#ySpeedRelative:-1

[movement]
movementType: NONE



