[core]
overrideAndReplace:commandCenter
name: spawner

displayText:Spawner
displayText_ru:Спавнер

class: CustomUnitMetadata
maxHp: 100000
price: 1
mass: 1
radius: 50
isBuilding: true
explodeTypeOnDeath: building
tags:unready, hq
isBuilder: true

@memory ready:boolean
@memory faction:number
[graphics]
image: spawner.png
drawLayer:bottom

[hiddenAction_fabLimit]
autoTriggerOnEvent: created
addResources:maxfabs=40

[hiddenAction_builder]
autoTriggerOnEvent: created
requireConditional: if self.numberOfUnitsInTeam(withTag='starterbuilder', lessThan=1)
spawnUnits: megaBuilder

[hiddenAction_readycheck]
autoTrigger:if numberOfUnitsInAllTeams(withTag="unready") <= 0
setUnitMemory:ready=true
showMessageToPlayer: All players ready, starting!

[hiddenAction_dominion]
autoTrigger:if memory.ready == true and memory.faction == 1
deleteSelf: true
spawnUnits: Dominion_HQ

[hiddenAction_ocullian]
autoTrigger:if memory.ready== true and memory.faction== 2
deleteSelf: true
spawnUnits: ocua_hq

[hiddenAction_fulgorian]
autoTrigger:if memory.ready== true and memory.faction== 3
deleteSelf: true
spawnUnits: fg_hq

[action_ready]
text:Ready up
text_ru:Готовность

isLocked: if not self.tags(includes='unready')
isLockedMessage: Already Ready!
isActive:if memory.faction != 0

description: Get ready for fightin
description_ru: Приготовится к пастуку

temporarilyRemoveTags:unready
showMessageToAllPlayers: %{self.playerName} is ready!
iconImage:ready_icon.png
ai_isHighPriority: true
autoTrigger:if self.isControlledByAI() and self.tags(includes='unready')

[action_choose_dominion]
text:Choose Dominion
text_ru:Выбрать Доминион

setUnitMemory:faction = 1
price:0
description: Choose Dominion \n \n-The Dominion is a human faction defending it's planet. They are faced with many otherworldly threats, but the indomitable human spirit lives on.
description_ru: \n-Доминион это человеческая фракция защищающая свою планету. Они сталкиваются с множеством иноземных угроз, но человеческая воля превозмагает.
displayType: upgrade
buildSpeed: 10
pos: 0.2

iconImage:dominion_icon.png
ai_isHighPriority: true
#guiBuildUnit:Dominion_HQ


[action_choose_ocua]
text:Choose Oculian
text_ru:Выбрать Окулиан

setUnitMemory:faction = 2
price:0
description: Choose Oculian Armada \n \n-The Oculian Armada is a collective of sentient rogue AIs from a galaxy far away, set free from their former masters.\n-Now in search of planets suitable to be turned into agri-world for their use.
description_ru: \n-Окулиан армада это коллектив ИИ с самосознанием из далёкой галактики, Освободившихся от своих прежних хозяев.\n-Теперь в поисках планет пригодных для превращения в аграрные для своих нужд.

displayType: upgrade
buildSpeed: 10
pos: 0.2

iconImage:oculian_icon.png
ai_isHighPriority: true
#guiBuildUnit:ocua_hq


[action_choose_fulgorian]
text:Choose fulgorian
text_ru:Выбрать Фулгору

setUnitMemory:faction = 3
price:0
description: Choose Fulgorian \n \n-The Fulgorians are otherwordly constructs built from the essence of Mount Fulghor from within another realm, it's wrath trascends the Fractures of reality to manifest within.\n-It wishes to capture new reals and territories untill nothing else remains
description_ru: \n-Фулгорцы это иномирные существа созданные из эссенции горы фулгор из другого измерений, её ярость преодолевает трещины реальности что-бы создать своих созданий.\n-Она желает захватить новые измерения и территории пока не останется ничего кроме её

displayType: upgrade
buildSpeed: 10
pos: 0.2

iconImage:fulgorian_icon.png
ai_isHighPriority: true
#guiBuildUnit:fg_hq


[action_fairactive]
text:Fairness system
text_ru:Система честности

isVisible: if self.teamId() == 0 and not self.numberOfUnitsInAllTeams(withTag='fair', greaterThan=0)
buildSpeed: 0
description: "Enables fairness system, giving extra money and hq income to unbalanced teams. Do not activate on FFA. Cannot be deactivated after clicking."
description_ru: Включить систему честности, Даёт дополнительные деньги и прирост экономики штабу меньшей команде. Не активировать в ФФА, не может быть выключено после включения
spawnUnits: fairnessSystem(neutralTeam=true)
showMessageToAllPlayers: Unbalanced Teams will now get extra starting cash and bonus hq income.



[arm_1]
x: 0
y: 0

drawOverBody:true

image_end:dominion_sigil.png
hidden: if memory.faction != 1
[arm_2]
x: 0
y: 0

drawOverBody:true

image_end:oculian_sigil.png
hidden: if memory.faction != 2

[arm_3]
x: 0
y: 0

drawOverBody:true


image_end:fulgorian_sigil.png
hidden: if memory.faction != 3

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 0