
[core]

name: anaconda

displayText: Anaconda SPAA
displayDescription: -High tech anti air tank\n-armed with a retrofitted gleam reverse-engineered from ocullian\n-air attack\n-MMMMMMMMMMMMM

displayText_ru: СПВО Анаконда
displayDescription_ru: Высокотехнологичная самоходная ПВО\n-Вооружена пересобранным орудием Глем окулиан\n-Воздушная атака\n-ММММММММММММММ

autoTriggerCheckRate:everyFrame
autoTriggerCooldownTime:0.05s
class: CustomUnitMetadata
price: credits=4800,thorium=280
maxHp: 2400
armour:5
mass: 8000

techLevel: 2
buildSpeed: 40s
#availableInDemo: true

radius: 25
displayRadius: 25

isBio: false
softCollisionOnAll: 0
autoTriggerCooldownTime: 0.2s

[graphics]
total_frames: 4

teamColorsOnTurret: true
image:        anaconda.png
image_wreak:  anaconda_wreck.png
image_turret: anaconda_turret.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 0
animation_moving_end: 3
animation_moving_speed: 2


dustEffect: true

[hiddenAction_prioritize]
autoTrigger: if self.isAttacking and not self.hasActiveWaypoint(type='attack') and self.numberOfUnitsInEnemyTeam(withTag='missile', greaterThan=0, withinRange=320) and not self.tags(includes='retreat')
addWaypoint_target_nearestUnit_tagged: missile
addWaypoint_target_nearestUnit_team: enemy
addWaypoint_type: attack
addWaypoint_prepend: true
addWaypoint_maxTime: 1s
allowMultipleInQueue:false

[hiddenAction_retreat]
autoTrigger: if self.isControlledByAi() and self.hp(lessThan=350) and not self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
temporarilyAddTags: retreat

[hiddenAction_retreating]
autoTrigger: if self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
allowMultipleInQueue:false

[hiddenAction_active]
autoTrigger: if self.tags(includes='retreat') and (self.hp() == self.maxHp())
temporarilyRemoveTags: retreat

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 20
turretTurnSpeed: 8
turretMultiTargeting:True

maxAttackRange: 400
shootDelay: 10



[turret_1]
#
x: 0
y: 7
invisible:true
attachedTo:base
slave:true

canAttackMaxAngle:25

projectile: 1

turnSpeed: 6
size:2
shoot_sound:ROOT:sounds\continuious_laser_1.wav
shoot_sound_vol:0.35
shoot_flame:none
canShoot: true


[projectile_1]
directDamage: 20
armourIgnoreAmount:5
deflectionPower: -1

speed:30

life: 30
drawSize: 1.5
instant: true
beamImageStart: SHARED:glow_sharp.png
beamImage: SHARED:beam3.png
beamImageEnd: SHARED:beam1_end.png

moveWithParent: true
explodeEffect: NONE
explodeEffectOnShield: NONE
color: #ff1b00

instantReuseLast:true
instantReuseLast_alsoChangeTurretAim:true

[turret_missile_1_r]
x: -12
y: -15


canAttackMaxAngle:45

invisible:true
attachedTo:base
slave:true

projectile:2
delay:300
warmup:10

shoot_sound:missile_fire
shoot_sound_vol:1.0
canOnlyAttackUnitsWithoutTags:missile

[turret_missile_2_r]
copyFrom:missile_1_r


x: -12
y: -10
linkDelayWithTurret:missile_1_r
warmup:30

[turret_missile_3_r]
copyFrom:missile_1_r


x: -12
y: -5
linkDelayWithTurret:missile_1_r
warmup:50

[turret_missile_4_r]
copyFrom:missile_1_r


x: -12
y: -0
linkDelayWithTurret:missile_1_r
warmup:70

[turret_missile_1_l]
copyFrom:missile_1_r

x: 12
y: -15
linkDelayWithTurret:missile_1_r
warmup:20
[turret_missile_2_l]
copyFrom:missile_1_r
x: 12
y: -10
linkDelayWithTurret:missile_1_r
warmup:40
[turret_missile_3_l]
copyFrom:missile_1_r
x: 12
y: -5
linkDelayWithTurret:missile_1_r
warmup:60

[turret_missile_4_l]
copyFrom:missile_1_r
x: 12
y: -0
linkDelayWithTurret:missile_1_r
warmup:80

[turret_base]
x: 0
y: 0
projectile: 1
canShoot:false

[projectile_2]
areaDamage: 80
areaRadius: 60

life: 500

speed: 2
targetSpeed: 26
targetSpeedAcceleration:0.5

trailEffect: true
largeHitEffect: true
frame: 4


autoTargetingOnDeadTarget: true
retargetingInFlight:true
retargetingInFlightSearchDelay:5
retargetingInFlightSearchRange:55
retargetingInFlightSearchLead:8

[attachment_extraLazer1]
x: 0
y: 6
isVisible: false
onCreateSpawnUnitOf: anaconda_laserAttachment
isUnselectable: true
deattachIfWantingToMove: false
rotateWithParent: true
resetRotationWhenNotAttacking: true
prioritizeParentsMainTarget: false
canBeAttackedAndDamaged:false
[attachment_extraLazer2]
@copyFromSection: attachment_extraLazer1
onCreateSpawnUnitOf: anaconda_laserAttachment2
x: 0
y: 5

[attachment_extraLazer3]
@copyFromSection: attachment_extraLazer1
onCreateSpawnUnitOf: anaconda_laserAttachment3
x: 0
y: 4

[movement]
movementType: LAND
moveSpeed: 0.7
moveAccelerationSpeed: 0.3
moveDecelerationSpeed: 0.4
reverseSpeedPercentage:0.7

maxTurnSpeed: 3.0
turnAcceleration: 0.65

moveSlidingMode :false
moveIgnoringBody:false

[ai]
buildPriority:0.4