[core]

name: anaconda_laserAttachment2
copyFrom:anaconda.ini
showInEditor: false

[graphics]
isVisible:false

[turret_1]
#
x: 0
y: 6
invisible:true
attachedTo:base
slave:true

canAttackMaxAngle:25

projectile: 1

turnSpeed: 6
size:2
shoot_sound:ROOT:sounds\continuious_laser_1.wav
shoot_sound_vol:0.0
shoot_flame:none
canShoot: true

warmup:5

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 20
turretTurnSpeed: 8
turretMultiTargeting:True

maxAttackRange: 400
shootDelay: 5

[attachment_extraLazer1]
x: 0
y: 5.8
isVisible: false
onCreateSpawnUnitOf: NONE
isUnselectable: true
deattachIfWantingToMove: false
rotateWithParent: true
resetRotationWhenNotAttacking: true
prioritizeParentsMainTarget: false

[attachment_extraLazer2]
x: 0
y: 5.8
isVisible: false
onCreateSpawnUnitOf: NONE
isUnselectable: true
deattachIfWantingToMove: false
rotateWithParent: true
resetRotationWhenNotAttacking: true
prioritizeParentsMainTarget: false

[attachment_extraLazer3]
x: 0
y: 5.8
isVisible: false
onCreateSpawnUnitOf: NONE
isUnselectable: true
deattachIfWantingToMove: false
rotateWithParent: true
resetRotationWhenNotAttacking: true
prioritizeParentsMainTarget: false
[turret_missile_1_r]
canShoot:false

[turret_missile_2_r]
copyFrom:missile_1_r

[turret_missile_3_r]
copyFrom:missile_1_r

[turret_missile_4_r]
copyFrom:missile_1_r

[turret_missile_1_l]
copyFrom:missile_1_r

[turret_missile_2_l]
copyFrom:missile_1_r

[turret_missile_3_l]
copyFrom:missile_1_r

[turret_missile_4_l]
copyFrom:missile_1_r