
[core]

name: auxilia

displayText: Auxilia MBT
displayDescription: -Light High Tech MBT of Dominion\n-low hp, but high shield, dps, and speed\n-equipped with retrofitted oculian shields, which have high regeneration but only out of combat.\n-Armed with a pulse lazer, which needs to recharge after burst fire.\n-Behold, xenotech!

displayText_ru: Ауксилия
displayDescription_ru: -Легкий высокотехнолгичный танк доминиона.\n-низкое хп, но сильные щиты, дпс, и скорость\n-Экипирован перенастроенными щитами окулиан, имеют высокую регенерацию но только вне боя.\n-Вооружен пульс лазером, что уходит на перезарядку после очереди.\n-Узрите,ксенотехнологии!

copyFrom:ROOT:Templates\customEffects.template

class: CustomUnitMetadata
price: credits=2200, thorium=160
maxHp: 350
maxShield:1400
shieldRegen:0.0

energyMax:7
energyRegen:0.005
energyNeedsToRechargeToFull:true
energyRegenWhenRecharging:0.04

mass: 5000
techLevel:3
buildSpeed: 35s
#availableInDemo: true

transportSlotsNeeded:2
radius: 24
displayRadius: 26
shieldRenderRadius:29

isBio: false
softCollisionOnAll: 0

[graphics]
total_frames: 4

teamColorsOnTurret: true
image:        auxilia.png
image_wreak:  auxilia_wreck.png
image_turret: auxilia_turret.png
image_shield: auxilia_shield.png
image_shadow: AUTO
shadowOffsetX:2.5
shadowOffsetY:2.5


animation_moving_start: 0
animation_moving_end: 3
animation_moving_speed: 3


dustEffect: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 15
turretTurnSpeed: 3


maxAttackRange: 220
shootDelay: 10

[turret_1]
#
x: 0
y: -7

projectile: 1

recoilOffset: -1
recoilReturnTime: 1.00s

aimOffsetSpread:0.2

turnSpeed: 3
barrelY: 20

canShoot: true
energyUsage: 1

shoot_light:#00f2ff
shoot_sound:plasma_fire
shoot_sound_vol:0.4
shoot_flame:None

canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
warmup:10

[projectile_1]
directDamage: 90
life: 5
speed: 9

instant:true
laserEffect:true

color: #59f7ff
lightColor: #74e9ff
lightSize: 0.5

beamImage:SHARED:beam1.png
beamImageStart:SHARED:beam1_start.png
beamImageEnd:SHARED:beam1_end.png

drawSize: 1.0


[movement]
movementType: LAND
moveSpeed: 1.0
moveAccelerationSpeed: 0.30
moveDecelerationSpeed: 0.40
reverseSpeedPercentage:0.9

maxTurnSpeed: 4.0
turnAcceleration: 0.75

moveSlidingMode :false
moveIgnoringBody:false

[hiddenAction_shieldRegenOn]
autoTrigger:if not self.hasTakenDamage(withinSeconds=15)
setUnitStats:shieldRegen=1.1
[hiddenAction_shieldRegenOff]
autoTrigger:if self.hasTakenDamage(withinSeconds=15)
setUnitStats:shieldRegen=0.0
[ai]
buildPriority:0.7