
[core]
name: fg_extractorT4
displayLocaleKey: extractorT4
copyFrom: fg_extractor.ini
price: 5200
maxHp: 1750
techLevel: 3
buildSpeed: 160s
displayText: Fulgorian Extractor T4
displayDescription: - +$25 income\n - Now generates +1 Holmium
generation_resources: credits=25, holmium=1
#generation_resources: credits=25, holmium=5

maxShield: 250
shieldRegen: 0.15
shieldRenderRadius: 24

[action_upgradeT5]
convertTo: fg_extractorT5
#price:  2500 #1.13.3 (with $+18)
price:  6000
text: Upgrade - T5
description: - More resource generation
displayType: upgrade
buildSpeed: 110s
iconExtraImage: SHARED:icon_upgrade_top.png
iconExtraColor: #AAFFFFFF

[action_upgradeT2]
isVisible: false

[action_divert]
convertTo: extractorT4_divert
price:  1000
text: Change Production
description: Swaps the resource focus to Holmium
displayType: upgrade
buildSpeed: 5s

[animation_idle]
KeyframeTimeScale: 0.28

[graphics]
image:        fg_extractor_t4.png


