[core]
name:heavy_howitzer

displayText: Heavy howitzer
displayDescription: -A Heavy artillery installation, for when the enemy is a certified tortoise \n-requires to be manned by 4 infantry to function \n-extra damage to buildings
copyFrom:ROOT:Templates\customEffects.template
price:8000
buildSpeed:150s
maxHp:3500
armour:3
isBuilding:true
mass:30000
radius:80

footprint: -2,-2,2,2
constructionFootprint: -2,-2,2,2

fogOfWarSightRange: 10

maxTransportingUnits: 4
transportUnitsRequireTag:infantry
transportUnitsRequireMovementType: LAND,OVER_CLIFF,HOVER

@memory target:unit

[graphics]
total_frames:2
imageScale:0.9
image:heavy_howitzer_gun.png
image_back:heavy_howitzer_base.png

image_wreak:heavy_howitzer_wreck.png

animation_moving_start: 1
animation_moving_end: 1
animation_moving_speed: 2
animation_idle_start: 1
animation_idle_end: 1
animation_idle_speed: 2
dustEffect: true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 600
shootDelay:1800
turretTurnSpeed:0.2
disablePassiveTargeting: true
isFixedFiring:true

[projectile_1]
areaDamage: 1200
areaRadius:140
deflectionPower:6
buildingDamageMultiplier:3

targetGround:true
disableLeadTargeting:true

alwaysVisibleInFog:true

life: 800

speed: 0.3
targetSpeed:2
targetSpeedAcceleration:0.020
ballistic_delaymove_height:0

initialUnguidedSpeedHeight: 0.6
gravity:0.7

lightColor: #ffe92b
lightSize: 0.4

color:#ff3200
image: ROOT:shared\graphics\howitser_shell.png

explodeEffect:CUSTOM:bigExplosion_2
explodeEffectOnShield:CUSTOM:bigExplosion_2

largeHitEffect: true
trailEffect: true

lightCastOnGround: true

targetGroundSpread:20

drawSize: 1.6

[turret_1]
x:0
y:0
canShoot:true
invisible:true
projectile:1
size:90
turnSpeed:0.20
idleDir:-90
shoot_sound:ROOT:sounds\howitzer_fire_2.wav
shoot_sound_vol:0.5
shoot_flame:large
shoot_light:#FFEEEEEE
shouldResetTurret:false


[turret_2]
x:0
y:0
idleDir:-90
shouldResetTurret:false
invisible:true
canShoot:false
turnSpeed:10
size:90
projectile:dummy
canAttackMaxAngle:181

[decal_faketurret]
basePositionFromTurret:2
yOffsetRelative:10
image:heavy_howitzer_barrel.png
teamColors:true
imageScaleY:min((0.85+((self.customTimer*self.customTimer)/29.0)+0.60*self.customTimer)-self.customTimer/1.25, 1)
layer:beforeBody

[attachment_slot1]
x:19
y:10
addTransportedUnits:true
rotateWithParent:true
canBeAttackedAndDamaged:true
canAttack:false
isUnselectable:true
idleDir:0
resetRotationWhenNotAttacking:true
keepAliveWhenParentDies:true
[attachment_slot2]
x:-22
y:-25
addTransportedUnits:true
rotateWithParent:true
canBeAttackedAndDamaged:true
isUnselectable:true
canAttack:false
idleDir:0
resetRotationWhenNotAttacking:true
keepAliveWhenParentDies:true
[attachment_slot3]
x:22
y:-25
addTransportedUnits:true
rotateWithParent:true
isUnselectable:true
canBeAttackedAndDamaged:true
canAttack:false
idleDir:0
resetRotationWhenNotAttacking:true
keepAliveWhenParentDies:true

[attachment_slot4]
x:-12
y:-36
addTransportedUnits:true
rotateWithParent:true
isUnselectable:true
canBeAttackedAndDamaged:true
canAttack:false
idleDir:-180
resetRotationWhenNotAttacking:true
keepAliveWhenParentDies:true

[action_fire]
text: FIRE!
displayType: action

isLocked: if self.transportingCount(lessThan=4)
isLockedMessage: needs to be manned by infantry to function

fireTurretXAtGround:1
fireTurretXAtGround_showGuideDecals: fire_point

whenBuilding_rotateTo_aimAtActionTarget:true
#whenBuilding_rotateTo_rotateTurretX:1
whenBuilding_rotateTo_waitTillRotated:true

resetCustomTimer:true

allowMultipleInQueue:false
buildSpeed:5s
addActionCooldownTime:25s
setUnitMemory:target=thisActionTarget()
alsoTriggerAction:spawn_decal
[hiddenAction_spawn_decal]
fireTurretXAtGround:2

[projectile_dummy]
life:100
areaDamage: 0
areaRadius:0
instant:true
targetGround:true
spawnUnit: heavy_warning
explodeOnEndOfLife:false
explodeEffect: NONE

[decal_fire_point]
image:fire_point.png
layer:inactive
alpha:0.5
imageScale:2

[decal_fire_point_approach]
image:fire_point_approach.png
layer:inactive
alpha:0.5
imageScale:2


[movement]
movementType:NONE
maxTurnSpeed:0.3
turnAcceleration:0.04

[ai]
disableUse:true