
[core]

name: sagittarii

displayText: Sagittarii tank
displayDescription: -Light self propelled tank hunter, more fragile than other tanks but boasts a longer range, stronger gun \n-ground attack


class: CustomUnitMetadata
price: 1000
maxHp: 400
armour:1
mass: 2000

techLevel: 1
buildSpeed: 11s
#availableInDemo: true

radius: 18
displayRadius: 18

isBio: false
softCollisionOnAll: 0

[graphics]
total_frames: 3
imageScale:0.8
teamColorsOnTurret: true
image:        sagittarii.png
image_wreak:  sagittarii_wreck.png
image_turret: sagittarii_turret_base.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 1


dustEffect: true

[hiddenAction_retreat]
autoTrigger: if self.isControlledByAi() and self.hp(lessThan=200) and not self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
temporarilyAddTags: retreat

[hiddenAction_retreating]
autoTrigger: if self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
allowMultipleInQueue:false

[hiddenAction_active]
autoTrigger: if self.tags(includes='retreat') and (self.hp() == self.maxHp())
temporarilyRemoveTags: retreat

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 10
turretTurnSpeed: 3


maxAttackRange: 180
shootDelay: 220

[turret_2]
#
x: 0
y: 0
image:sagittarii_turret_barrel.png
attachedTo:1
slave:true

projectile: 1

warmup:20

recoilOffset: -5
recoilReturnTime: 1.00s

turnSpeed: 3
barrelY: 25

canShoot: true

shoot_sound:ROOT:sounds\tank_fire_1.wav
shoot_sound_vol:0.080
shoot_flame:small


[turret_1]
x: 0
y: 0
projectile: 1
canShoot:false


[projectile_1]
directDamage: 170
life: 80
speed: 7
color:#ff9600
image: ROOT:shared\graphics\shell.png
drawSize: 0.8


[movement]
movementType: LAND
moveSpeed: 0.8
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.10
reverseSpeedPercentage:0.90

maxTurnSpeed: 2.5
turnAcceleration: 0.4

moveSlidingMode :false
moveIgnoringBody:false

[ai]
buildPriority:0.7