[core]
name: flux

displayText: Flux Hover
displayDescription: -Hover lightning vehicle \n-armed with an improved continuous tesla coil which can deal damage to multiple units at once\n-extra damage to shielded units\n-split shots are weaker\n-Land and Air attack

class: CustomUnitMetadata
price: 1600
maxHp: 800

mass: 2000

techLevel: 2
buildSpeed: 21s
#availableInDemo: true

radius: 17
displayRadius: 13

isBio: false
softCollisionOnAll: 0


[graphics]
total_frames: 2

teamColorsOnTurret: true
image:        flux.png
image_wreak:  flux_wreck.png
image_turret: flux_turret.png

image_shadow: AUTO
shadowOffsetX:2
shadowOffsetY:2


animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 3

animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 6

splastEffect: true
dustEffect: true

[hiddenAction_prioritize]
autoTrigger: if self.isControlledByAi() and self.isAttacking and self.numberOfUnitsInEnemyTeam(withTag='shield', greaterThan=0, withinRange=200) and not self.tags(includes='retreat')
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: shield
addWaypoint_target_nearestUnit_team: enemy
addWaypoint_type: attack
allowMultipleInQueue:false

[hiddenAction_retreat]
autoTrigger: if self.isControlledByAi() and self.hp(lessThan=150) and not self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
temporarilyAddTags: retreat

[hiddenAction_retreating]
autoTrigger: if self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
allowMultipleInQueue:false

[hiddenAction_active]
autoTrigger: if self.tags(includes='retreat') and (self.hp() == self.maxHp())
temporarilyRemoveTags: retreat

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 12

maxAttackRange: 190

shootDelay: 10

[turret_1]
#coil
x: 0
y: 0

projectile: 1

turnSpeed: 6
turnSpeedAcceleration: 4
barrelY:23
shoot_sound:lighting_burst
shoot_sound_vol:0.15
shoot_flame:CUSTOM:sparks2*1
shoot_light:#FFcceeee

canShoot: true

chargeEffectImage: SHARED:lighting_charge.png


[projectile_1]
spawnUnit:domi_chainBeam
directDamage: 9
life: 25

instant: true
instantReuseLast:true
moveWithParent:true

lightingEffect: true
largeHitEffect: true


shieldDamageMultiplier: 3.0
shieldDefectionMultiplier:0.8

explodeEffect:CUSTOM:lightningShock, CUSTOM:sparks*2


explodeEffectOnShield:CUSTOM:hitLightFlash, CUSTOM:sparks*2


[effect_hitLightFlash]
priority:high

image: SHARED:light_50.png
life: 17
fadeOut: true
attachedToUnit: false
color: #63e6e8

scaleFrom: 1.8
scaleTo: 1.8
alpha: 0.6
drawUnderUnits:false


[effect_lightningShock]
life: 60


hOffset: 0
dirOffset: 0

fadeInTime: 0
fadeOut: false

attachedToUnit: true


image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5



[effect_sparks]
attachedToUnit: false
life: 150
physics: true
xSpeedRelativeRandom: 1.6
ySpeedRelativeRandom: 1.6
hSpeed: 2
image: SHARED:spark.png
priority: verylow

[effect_sparks2]
attachedToUnit: false
life: 150
physics: true
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.5
hSpeed: 1
image: SHARED:spark.png
priority: verylow

[movement]
movementType: HOVER
moveSpeed: 1.2
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.01

targetHeight:4
reverseSpeedPercentage:0.5
targetHeightDrift:0.5
heightChangeRate:0.1


maxTurnSpeed: 3.2
turnAcceleration: 1.0

moveSlidingMode :true
moveIgnoringBody:true





