
[core]

name: onager

displayText: Onager tank
displayDescription: -Self propelled tank hunter "Onager"\n-more fragile than other tanks but boasts a longer range\n-Strong gun with low firerate  \n-ground attack

displayText_ru: Танк Онагр
displayDescription_ru:-Самоходное противотанковое орудие "Онагр"\n-Более хрупкий чем другие танки, но имеет большую дальность\n-Мощное орудие с низкой скорострельностью\n-Наземная атака

class: CustomUnitMetadata
price: 2800
maxHp: 1200
armour:3
mass: 2000

techLevel: 2
buildSpeed: 26s
#availableInDemo: true

radius: 26
displayRadius: 26

isBio: false
softCollisionOnAll: 0

[graphics]
total_frames: 3
imageScale:0.9
teamColorsOnTurret: true
image:       onager.png
image_wreak:  onager_wreck.png
image_turret: onager_turret_base.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 1


dustEffect: true

[hiddenAction_retreat]
autoTrigger: if self.isControlledByAi() and self.hp(lessThan=200) and not self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
temporarilyAddTags: retreat

[hiddenAction_retreating]
autoTrigger: if self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
allowMultipleInQueue:false

[hiddenAction_active]
autoTrigger: if self.tags(includes='retreat') and (self.hp() == self.maxHp())
temporarilyRemoveTags: retreat

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 10
turretTurnSpeed: 3


maxAttackRange: 260
shootDelay: 310

[turret_2]
#
x: 0
y: 36
image:onager_turret_barrel.png
attachedTo:1
slave:true

projectile: 1

warmup:20

recoilOffset: -8
recoilReturnTime: 3.00s

turnSpeed: 3
barrelY: 25

canShoot: true

shoot_sound:ROOT:sounds\tank_fire_5.wav
shoot_sound_vol:0.400
shoot_flame:small


[turret_1]
x: 0
y: -2
projectile: 1
canShoot:false


[projectile_1]
directDamage: 560
life: 120
speed: 10
color:#ff9600
image: ROOT:shared\graphics\shell.png
drawSize: 1.0


[movement]
movementType: LAND
moveSpeed: 0.70
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.10
reverseSpeedPercentage:0.90

maxTurnSpeed: 2.5
turnAcceleration: 0.4

moveSlidingMode :false
moveIgnoringBody:false

[ai]
buildPriority:0.7