
[core]
name: falcon
class: CustomUnitMetadata
price: 550
maxHp: 280
mass: 2000

copyFrom:ROOT:Templates\customEffects.template

energyMax: 12
energyRegen: 0.01
energyRegenWhenRecharging:0.10
energyNeedsToRechargeToFull: true

displayText: Falcon interceptor
displayDescription:- A plane interceptor
techLevel: 1
buildSpeed: 7.0s

radius: 15

isBio: false

softCollisionOnAll: 40
fogOfWarSightRange: 16
tags: air

[graphics]
total_frames: 14
drawLayer:air
animation_moving_start: 0
animation_moving_end: 7
animation_moving_speed: 0.5

image:        falcon.png
image_wreak:  falcon_wreck.png
image_turret: NONE
imageScale:0.9
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1

[attack]

canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
attackMovement: bomber
turretSize: 18
turretTurnSpeed: 20
maxAttackRange: 300
shootDelay: 5
turretMultiTargeting:true
isMelee:true

[turret_retreatDistance]
x: 0
y: 0
invisible: true
shoot_flame: NONE
canShoot:true
limitingRange:300
projectile:dummy
delay:100

[projectile_dummy]
life: 1

directDamage: 0
areaDamage: 0
areaRadius: 0

speed: 1
instant: false

invisible: true
hitSound: false
explodeEffect: NONE
explodeEffectOnShield: NONE
trailEffect: false
largeHitEffect: false

[turret_2]
x: 0
y: 0

barrelX:-10
barrelY:10
barrelOffsetX_onOddShots: 20
idleDir:0
invisible: true
canAttackCondition: if self.flying
canShoot: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
energyUsage:1
projectile: dummy
limitingRange:260
turnSpeed: 20
canAttackMaxAngle:65
limitingAngle:65

[attachment_RealGun]
x:0
y:0

idleDir: 0
onCreateSpawnUnitOf:falcon_gun
isUnselectable: true
deattachIfWantingToMove: false
rotateWithParent: true
resetRotationWhenNotAttacking: true
prioritizeParentsMainTarget: true

isVisible:true
setDrawLayerOnTop:true

[movement]
movementType: AIR
moveSpeed: 2.5
moveAccelerationSpeed: 0.5
moveDecelerationSpeed: 0.02
reverseSpeedPercentage:0.0
landOnGround: onlyIdle


maxTurnSpeed: 6.0
#turnAcceleration: 0.20

moveSlidingMode :true
moveIgnoringBody:false


targetHeight:60
heightChangeRate:0.8

slowDeathFall: true
