
[core]

name: halberd

displayText: Halberd HCV
displayDescription: -Heavy combat vehicle "Halberd"\n-tough for it's speed \n-ground attack and light AA

copyFrom:ROOT:Templates\customEffects.template

class: CustomUnitMetadata
price: 2500
maxHp: 2000
mass: 2200
armour:5

techLevel: 2
buildSpeed: 35s
#availableInDemo: true

radius: 22
displayRadius: 24

isBio: false
softCollisionOnAll: 0

[graphics]
total_frames: 3

imageScale:1.1
scaleTurretImagesTo: 32

teamColorsOnTurret: true
image:        halberd.png
image_wreak:  halberd_wreck.png
image_turret: halberd_turret_base.png

image_shadow: AUTO
shadowOffsetX:2
shadowOffsetY:2

dustEffect: true

animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 1

[hiddenAction_retreat]
autoTrigger: if self.isControlledByAi() and self.hp(lessThan=200) and not self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
temporarilyAddTags: retreat

[hiddenAction_retreating]
autoTrigger: if self.tags(includes='retreat')
requireConditional: if self.numberOfUnitsInTeam(withTag='repair', greaterThan=0, withinRange=1000)
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
allowMultipleInQueue:false

[hiddenAction_active]
autoTrigger: if self.tags(includes='retreat') and (self.hp() == self.maxHp())
temporarilyRemoveTags: retreat

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 10
turretTurnSpeed: 5


maxAttackRange: 200
shootDelay: 30


[turret_3]
x: 0
y: 0
projectile: 2
delay:8
shoot_sound:ROOT:sounds\lmg_fire_2.wav
shoot_sound_vol:0.10
shoot_flame:small
shoot_light:#FFccCCEE
image:halberd_turret_mg.png
attachedTo:1
slave:true
canAttackMaxAngle:45
barrelX:5
barrelY:14
recoilOffset: -3
recoilReturnTime: 0.10s

[projectile_2]
directDamage: 7
life: 60
speed: 9

frame: 5

drawSize: 0.6

explodeEffect:CUSTOM:bullet_hit

[turret_2]
#
warmup:12

x: 0
y: 6
image:halberd_turret_barrel.png
attachedTo:1
slave:true
canAttackFlyingUnits: false
projectile: 1

recoilOffset: -6
recoilReturnTime: 0.20s

turnSpeed: 5
barrelY: 10

canShoot: true


shoot_sound:ROOT:sounds\tank_fire_2.wav
shoot_sound_vol:0.110
shoot_flame:small

[turret_1]
x: 0
y: 0
projectile: 1
canShoot:false


[projectile_1]
directDamage: 50
areaDamage:20
areaRadius:30

life: 80
speed: 8

frame: 1
drawSize: 1


[movement]
movementType: LAND
moveSpeed: 1.00
moveAccelerationSpeed: 0.2
moveDecelerationSpeed: 0.3
reverseSpeedPercentage:0.7

maxTurnSpeed: 5.0
turnAcceleration: 0.55

moveSlidingMode :false
moveIgnoringBody:false

[ai]
buildPriority:0.7