[core]

name: light_veh_fac_t3
class: CustomUnitMetadata
maxHp: 2200
price: credits=5300, thorium=80
mass: 1000
copyFrom:light_veh_fac_t2.ini
displayText: Vehicle Factory T3
displayDescription: -Dominion's High-tech Vehicle Factory\n-Produces high-tech vehicles of dominion featuring stolen and adapted technology.\n-existance of a t3 factory allows for faster and cheaper upgrades of t2 factories of this type

displayText: Завод легкой техники Т3
displayDescription:-Высокотехнологичный завод легкой техники доминиона\n-Производит высокотехнологичную технику доминиона имеющию украденные и адаптированные технологии.\n-Наличие т3 завода позволит быстрее и дешевле прокачать остальные т2 заводы этого типа

tags:T3_vehicles
nanoFactorySpeed: 1.50
techLevel:3

radius: 60
displayRadius:60

buildSpeed: 80s

#footprint used for collisions with units (left, up, right, down)
footprint: -1,-1,1,1

#used for placement, and placement of other buildings
constructionFootprint: -1,-1,1,1

isBuilding: true
explodeTypeOnDeath: building

canBuild_1_name: setRally
canBuild_1_pos:  0.1


canBuild_11_name: champion
canBuild_11_pos:  11
[graphics]

image: light_veh_fac_t3.png
image_back: light_veh_fac_bottom_t3.png
image_wreak: light_veh_fac_wreck_t3.png

image_shadow: auto
shadowOffsetX:1
shadowOffsetY:1

total_frames: 8

animation_idle_start:0
animation_idle_end:7
animation_idle_speed:6

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false

[action_upgrade]
isVisible:false

[action_upgrade_consecutive]
isVisible:false

[arm_1]
x:0
y:-6
image_end:light_veh_fac_t2_door.png
image_end_teamColors:true

[animation_openDoor]

onActions: queuedUnits
onActionsQueuedUnitPlayAt: 0.8

blendIn: 1s
blendOut: 4s

arm1_0: {x:0, y:26}

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1

[ai]
upgradedFrom: light_veh_fac